// GENERATED FILE — DO NOT EDIT.
//
// Written by web/scripts/export-public-content.mts from web/content/public/*.ts, which is
// the single source of truth for Screen Inventory §2.0's curated catalog and copy.
// Regenerate with:  npm run generate:public-content
//
// CI fails when this file is stale, so the phone and the browser cannot show a traveler
// different words or a different price for the same trip.
@file:Suppress("MaxLineLength", "LargeClass")

package com.storytail.adventures.content.public

internal object PublicCatalog {

    val TRIPS: List<Trip> = listOf(
        Trip(
            slug = "beaches-turks-and-caicos",
            name = "Beaches Turks & Caicos",
            tagline = "Providenciales · Family all-inclusive",
            overline = "ALL-INCLUSIVE · FAMILY",
            type = TripType.ALL_INCLUSIVE,
            vibes = listOf(
                Vibe.FAMILY,
            ),
            topics = mapOf(
                Topic.CARIBBEAN to TopicPlacement(order = 1, overline = null, tagline = null, badge = "Gyasi's pick"),
            ),
            destination = Destination(place = "Providenciales, Turks & Caicos", region = "Caribbean", island = "turks-and-caicos"),
            nights = 7,
            band = PriceBand.TWO,
            from = Money(amountCents = 264000L, currency = "USD"),
            priceAsOf = "2026-09-02",
            pricePlaceholder = true,
            priceNote = "Starting price shown in the design — request a quote for real prices on your dates.",
            badge = "Gyasi's pick",
            imageKey = "turks",
            heroImageKey = null,
            description = "Grace Bay's long white beach out front, a waterpark the kids will talk about for a year, and enough places to eat that nobody has to agree on dinner. Built for families who want the week handled before they land.",
            highlights = listOf(
                TripHighlight(icon = "users", text = "Family suites and kids' camps by age"),
                TripHighlight(icon = "palm", text = "Grace Bay beach on your doorstep"),
                TripHighlight(icon = "utensils", text = "Every meal and snack included"),
                TripHighlight(icon = "plane", text = "Flights and transfers arranged for you"),
            ),
            sampleItinerary = listOf(
                "Day 1 · Arrive, unpack once, first sunset on Grace Bay",
                "Day 2 · Waterpark morning, quiet beach afternoon",
                "Day 3 · Reef snorkel trip for the whole family",
                "Day 4 · Resort day — spa for the grown-ups, kids' camp for the rest",
            ),
            line = null,
        ),
        Trip(
            slug = "sandals-royal-bahamian",
            name = "Sandals Royal Bahamian",
            tagline = "Nassau · Adults-only · 7 nights",
            overline = "ALL-INCLUSIVE · ADULTS",
            type = TripType.ALL_INCLUSIVE,
            vibes = listOf(
                Vibe.ADULTS_ONLY,
                Vibe.COUPLES,
                Vibe.HONEYMOON,
            ),
            topics = mapOf(
                Topic.CARIBBEAN to TopicPlacement(order = 2, overline = null, tagline = null, badge = null),
                Topic.HONEYMOONS to TopicPlacement(order = 6, overline = null, tagline = "Nassau · Private island day · 7 nights", badge = null),
            ),
            destination = Destination(place = "Nassau, Bahamas", region = "Caribbean", island = "bahamas"),
            nights = 7,
            band = PriceBand.THREE,
            from = Money(amountCents = 329000L, currency = "USD"),
            priceAsOf = "2026-09-02",
            pricePlaceholder = true,
            priceNote = "All-in · flights, transfers, all meals, drinks, activities",
            badge = null,
            imageKey = "bahamas",
            heroImageKey = "overwater",
            description = "Over-water bungalows, six pools, twelve dining venues, a Red Lane spa, and a private island day. Adults-only — built for honeymoons, anniversaries, and “just us” weeks.",
            highlights = listOf(
                TripHighlight(icon = "plane", text = "Flights included from MIA"),
                TripHighlight(icon = "utensils", text = "12 restaurants"),
                TripHighlight(icon = "heart", text = "Red Lane spa credit"),
                TripHighlight(icon = "ship", text = "Day-trip to Rose Island"),
            ),
            sampleItinerary = listOf(
                "Day 1 · Arrival & sunset welcome",
                "Day 2 · Beach + Red Lane spa",
                "Day 3 · Rose Island Cay snorkel",
                "Day 4 · Resort day",
            ),
            line = null,
        ),
        Trip(
            slug = "sandals-grande-st-lucian",
            name = "Sandals Grande St. Lucian",
            tagline = "Rodney Bay, St. Lucia · Overwater bungalows · 7 nights",
            overline = "ALL-INCLUSIVE · COUPLES",
            type = TripType.ALL_INCLUSIVE,
            vibes = listOf(
                Vibe.ADULTS_ONLY,
                Vibe.COUPLES,
                Vibe.HONEYMOON,
            ),
            topics = mapOf(
                Topic.CARIBBEAN to TopicPlacement(order = 3, overline = null, tagline = "Rodney Bay · Lush rainforest views", badge = null),
                Topic.HONEYMOONS to TopicPlacement(order = 1, overline = "OVERWATER · ADULTS", tagline = "St. Lucia · Overwater bungalows · 7 nights", badge = "Gyasi's pick"),
            ),
            destination = Destination(place = "Rodney Bay, St. Lucia", region = "Caribbean", island = "st-lucia"),
            nights = 7,
            band = PriceBand.THREE,
            from = Money(amountCents = 389000L, currency = "USD"),
            priceAsOf = "2026-09-02",
            pricePlaceholder = true,
            priceNote = "Illustrative starting price — request a quote for real prices on your dates.",
            badge = null,
            imageKey = "stlucia",
            heroImageKey = null,
            description = "A calm bay on one side, the Pitons on the horizon, and a handful of over-water bungalows for the couples who want the ocean under the floorboards. The spa here is the one Gyasi sends honeymooners to first.",
            highlights = listOf(
                TripHighlight(icon = "heart", text = "Over-water bungalows with glass floors"),
                TripHighlight(icon = "palm", text = "Rainforest and Piton views"),
                TripHighlight(icon = "utensils", text = "All meals, drinks and dining venues included"),
                TripHighlight(icon = "plane", text = "Flights and transfers arranged for you"),
            ),
            sampleItinerary = listOf(
                "Day 1 · Arrive, settle in, dinner over the water",
                "Day 2 · Spa morning, bay afternoon",
                "Day 3 · Piton catamaran day",
                "Day 4 · Nothing planned — on purpose",
            ),
            line = null,
        ),
        Trip(
            slug = "couples-negril",
            name = "Couples Negril",
            tagline = "Negril · Quiet, all-inclusive, no kids",
            overline = "ALL-INCLUSIVE · COUPLES",
            type = TripType.ALL_INCLUSIVE,
            vibes = listOf(
                Vibe.ADULTS_ONLY,
                Vibe.COUPLES,
            ),
            topics = mapOf(
                Topic.CARIBBEAN to TopicPlacement(order = 4, overline = null, tagline = null, badge = null),
            ),
            destination = Destination(place = "Negril, Jamaica", region = "Caribbean", island = "jamaica"),
            nights = 7,
            band = PriceBand.TWO,
            from = Money(amountCents = 218000L, currency = "USD"),
            priceAsOf = "2026-09-02",
            pricePlaceholder = true,
            priceNote = "Starting price shown in the design — request a quote for real prices on your dates.",
            badge = null,
            imageKey = "jamaica",
            heroImageKey = null,
            description = "Seven-mile beach, a slower pace, and a resort that has been quietly good for decades. No kids, no upsells, no reason to look at your phone. The week Gyasi suggests when a couple says “we just need to stop.”",
            highlights = listOf(
                TripHighlight(icon = "palm", text = "Seven Mile Beach"),
                TripHighlight(icon = "heart", text = "Couples-only, unhurried"),
                TripHighlight(icon = "utensils", text = "Meals, drinks and excursions included"),
                TripHighlight(icon = "ship", text = "Sunset catamaran sail"),
            ),
            sampleItinerary = listOf(
                "Day 1 · Arrive, first swim before dinner",
                "Day 2 · Beach day, glass-bottom boat",
                "Day 3 · Cliff-jumping (optional) and reggae sunset",
                "Day 4 · Spa and a long, slow lunch",
            ),
            line = null,
        ),
        Trip(
            slug = "bucuti-and-tara",
            name = "Bucuti & Tara Beach Resort",
            tagline = "Eagle Beach, Aruba · Boutique adult-only",
            overline = "BOUTIQUE · ADULTS",
            type = TripType.HOTEL,
            vibes = listOf(
                Vibe.ADULTS_ONLY,
                Vibe.BOUTIQUE,
                Vibe.COUPLES,
            ),
            topics = mapOf(
                Topic.CARIBBEAN to TopicPlacement(order = 5, overline = null, tagline = "Eagle Beach · Boutique adult-only", badge = null),
            ),
            destination = Destination(place = "Eagle Beach, Aruba", region = "Caribbean", island = "aruba"),
            nights = 7,
            band = PriceBand.THREE,
            from = Money(amountCents = 345000L, currency = "USD"),
            priceAsOf = "2026-09-02",
            pricePlaceholder = true,
            priceNote = "Illustrative starting price — request a quote for real prices on your dates.",
            badge = null,
            imageKey = "aruba",
            heroImageKey = null,
            description = "A small, adults-only resort on one of the Caribbean's widest beaches, in the island with the most reliable sunshine. Quiet by design — for couples who want a boutique feel rather than a big all-inclusive.",
            highlights = listOf(
                TripHighlight(icon = "palm", text = "Eagle Beach, steps from your room"),
                TripHighlight(icon = "heart", text = "Adults-only, boutique scale"),
                TripHighlight(icon = "star", text = "Consistently sunny, outside the hurricane belt"),
                TripHighlight(icon = "utensils", text = "Beachfront dining"),
            ),
            sampleItinerary = listOf(
                "Day 1 · Arrive, sunset on Eagle Beach",
                "Day 2 · Beach palapa and a long swim",
                "Day 3 · Arikok National Park half-day",
                "Day 4 · Spa and an island-side dinner",
            ),
            line = null,
        ),
        Trip(
            slug = "atlantis-paradise-island",
            name = "Atlantis Paradise Island",
            tagline = "Nassau · Waterpark + family suites",
            overline = "RESORT · FAMILY",
            type = TripType.HOTEL,
            vibes = listOf(
                Vibe.FAMILY,
                Vibe.GROUP,
            ),
            topics = mapOf(
                Topic.CARIBBEAN to TopicPlacement(order = 6, overline = null, tagline = null, badge = null),
            ),
            destination = Destination(place = "Paradise Island, Bahamas", region = "Caribbean", island = "bahamas"),
            nights = 5,
            band = PriceBand.TWO,
            from = Money(amountCents = 219000L, currency = "USD"),
            priceAsOf = "2026-09-02",
            pricePlaceholder = true,
            priceNote = "Illustrative starting price — request a quote for real prices on your dates.",
            badge = null,
            imageKey = "bahamas",
            heroImageKey = null,
            description = "The big one: waterpark, aquarium, lagoons, and enough towers that Gyasi will steer you to the right one for your family's age range and budget. Not an all-inclusive — which is why having someone plan the meals matters.",
            highlights = listOf(
                TripHighlight(icon = "users", text = "Waterpark and aquarium on property"),
                TripHighlight(icon = "star", text = "Towers for every budget"),
                TripHighlight(icon = "plane", text = "Short flights from most of the East Coast"),
                TripHighlight(icon = "utensils", text = "Dining plan options Gyasi will explain"),
            ),
            sampleItinerary = listOf(
                "Day 1 · Arrive, lagoon swim before dinner",
                "Day 2 · Waterpark from opening bell",
                "Day 3 · Aquarium morning, beach afternoon",
                "Day 4 · Nassau day trip or a slow pool day",
            ),
            line = null,
        ),
        Trip(
            slug = "excellence-oyster-bay",
            name = "Excellence Oyster Bay",
            tagline = "Falmouth, Jamaica · Adults-only all-inclusive",
            overline = "ALL-INCLUSIVE · ADULTS",
            type = TripType.ALL_INCLUSIVE,
            vibes = listOf(
                Vibe.ADULTS_ONLY,
                Vibe.COUPLES,
            ),
            topics = mapOf(
                Topic.CARIBBEAN to TopicPlacement(order = 7, overline = null, tagline = "Falmouth · Adults-only all-inclusive", badge = null),
            ),
            destination = Destination(place = "Falmouth, Jamaica", region = "Caribbean", island = "jamaica"),
            nights = 7,
            band = PriceBand.TWO,
            from = Money(amountCents = 236000L, currency = "USD"),
            priceAsOf = "2026-09-02",
            pricePlaceholder = true,
            priceNote = "Illustrative starting price — request a quote for real prices on your dates.",
            badge = null,
            imageKey = "jamaica",
            heroImageKey = null,
            description = "An adults-only all-inclusive on its own peninsula between Montego Bay and Ocho Rios. Over-water bungalows, swim-up suites, and a quieter stretch of Jamaica than the big-resort strips.",
            highlights = listOf(
                TripHighlight(icon = "heart", text = "Over-water and swim-up suites"),
                TripHighlight(icon = "palm", text = "Private peninsula, calm water"),
                TripHighlight(icon = "utensils", text = "All dining and drinks included"),
                TripHighlight(icon = "plane", text = "About 40 minutes from Montego Bay airport"),
            ),
            sampleItinerary = listOf(
                "Day 1 · Arrive, first dinner by the water",
                "Day 2 · Pool and beach, no agenda",
                "Day 3 · Dunn's River Falls day trip",
                "Day 4 · Spa and a sunset sail",
            ),
            line = null,
        ),
        Trip(
            slug = "bvi-sailing-charter",
            name = "BVI sailing charter",
            tagline = "7-night skippered catamaran",
            overline = "SAILING · GROUP",
            type = TripType.TOUR,
            vibes = listOf(
                Vibe.GROUP,
                Vibe.ADVENTURE,
                Vibe.COUPLES,
            ),
            topics = mapOf(
                Topic.CARIBBEAN to TopicPlacement(order = 8, overline = null, tagline = null, badge = "Great for groups"),
            ),
            destination = Destination(place = "British Virgin Islands", region = "Caribbean", island = "bvi"),
            nights = 7,
            band = PriceBand.THREE,
            from = Money(amountCents = 495000L, currency = "USD"),
            priceAsOf = "2026-09-02",
            pricePlaceholder = true,
            priceNote = "Illustrative starting price — request a quote for real prices on your dates.",
            badge = "Great for groups",
            imageKey = "bvi",
            heroImageKey = null,
            description = "A skippered catamaran for six to ten people, island-hopping the BVI for a week. Somebody else sails, cooks and picks the anchorage; you snorkel, read, and watch the light change. Gyasi's favorite way to do a friends' week.",
            highlights = listOf(
                TripHighlight(icon = "ship", text = "Skippered catamaran, your own itinerary"),
                TripHighlight(icon = "users", text = "Best for 6–10 travelers"),
                TripHighlight(icon = "palm", text = "A new anchorage every night"),
                TripHighlight(icon = "star", text = "Snorkel straight off the boat"),
            ),
            sampleItinerary = listOf(
                "Day 1 · Board in Tortola, first anchorage by sunset",
                "Day 2 · The Baths at Virgin Gorda",
                "Day 3 · Anegada's reef and beach bars",
                "Day 4 · Jost Van Dyke, an easy afternoon",
            ),
            line = null,
        ),
        Trip(
            slug = "beaches-negril",
            name = "Beaches Negril",
            tagline = "Negril · Sesame Street + 7 beaches",
            overline = "ALL-INCLUSIVE · FAMILY",
            type = TripType.ALL_INCLUSIVE,
            vibes = listOf(
                Vibe.FAMILY,
            ),
            topics = mapOf(
                Topic.CARIBBEAN to TopicPlacement(order = 9, overline = null, tagline = null, badge = null),
            ),
            destination = Destination(place = "Negril, Jamaica", region = "Caribbean", island = "jamaica"),
            nights = 7,
            band = PriceBand.TWO,
            from = Money(amountCents = 248000L, currency = "USD"),
            priceAsOf = "2026-09-02",
            pricePlaceholder = true,
            priceNote = "Illustrative starting price — request a quote for real prices on your dates.",
            badge = null,
            imageKey = "overwater",
            heroImageKey = null,
            description = "The family Beaches on Seven Mile Beach: character breakfasts for the little ones, a waterpark for the middle ones, and a quiet corner for the parents. Everything included, so the only decision is which beach.",
            highlights = listOf(
                TripHighlight(icon = "users", text = "Kids' camps and character programming"),
                TripHighlight(icon = "palm", text = "Seven Mile Beach"),
                TripHighlight(icon = "utensils", text = "All meals, snacks and drinks included"),
                TripHighlight(icon = "plane", text = "Flights and transfers arranged for you"),
            ),
            sampleItinerary = listOf(
                "Day 1 · Arrive, beach before dinner",
                "Day 2 · Waterpark and character breakfast",
                "Day 3 · Glass-bottom boat and reef swim",
                "Day 4 · Parents' spa morning, kids' camp",
            ),
            line = null,
        ),
        Trip(
            slug = "symphony-of-the-seas",
            name = "Symphony of the Seas",
            tagline = "Eastern Caribbean · 7 nights · From Miami",
            overline = "ROYAL CARIBBEAN",
            type = TripType.CRUISE,
            vibes = listOf(
                Vibe.FAMILY,
                Vibe.GROUP,
            ),
            topics = mapOf(
                Topic.CRUISES to TopicPlacement(order = 1, overline = null, tagline = null, badge = "Gyasi's pick"),
            ),
            destination = Destination(place = "Eastern Caribbean from Miami", region = "Caribbean", island = null),
            nights = 7,
            band = PriceBand.TWO,
            from = Money(amountCents = 185000L, currency = "USD"),
            priceAsOf = "2026-09-02",
            pricePlaceholder = true,
            priceNote = "Starting price shown in the design — request a quote for real prices on your dates.",
            badge = "Gyasi's pick",
            imageKey = "cruiseShip",
            heroImageKey = null,
            description = "One of the biggest ships afloat, which is exactly the point for a multi-generation family: a waterslide deck for the kids, a quiet solarium for the grandparents, and a private island day at Perfect Day at CocoCay.",
            highlights = listOf(
                TripHighlight(icon = "users", text = "Built for multi-gen families"),
                TripHighlight(icon = "ship", text = "Perfect Day at CocoCay"),
                TripHighlight(icon = "utensils", text = "Dozens of dining venues"),
                TripHighlight(icon = "plane", text = "Sails from Miami"),
            ),
            sampleItinerary = listOf(
                "Day 1 · Board in Miami, sail-away on deck",
                "Day 2 · Perfect Day at CocoCay",
                "Day 3 · Sea day — waterslides and the solarium",
                "Day 4 · St. Thomas beach day",
            ),
            line = "Royal Caribbean",
        ),
        Trip(
            slug = "disney-fantasy",
            name = "Disney Fantasy",
            tagline = "Western Caribbean · 7 nights · Castaway Cay",
            overline = "DISNEY · FAMILY",
            type = TripType.CRUISE,
            vibes = listOf(
                Vibe.FAMILY,
            ),
            topics = mapOf(
                Topic.CRUISES to TopicPlacement(order = 2, overline = null, tagline = null, badge = null),
            ),
            destination = Destination(place = "Western Caribbean from Port Canaveral", region = "Caribbean", island = null),
            nights = 7,
            band = PriceBand.THREE,
            from = Money(amountCents = 342000L, currency = "USD"),
            priceAsOf = "2026-09-02",
            pricePlaceholder = true,
            priceNote = "Illustrative starting price — request a quote for real prices on your dates.",
            badge = null,
            imageKey = "cruiseAerial",
            heroImageKey = null,
            description = "The Disney week: character meet-ups, rotational dining, a kids' club that parents have to drag children out of, and Castaway Cay. Pricier than the other family lines, and Gyasi will tell you honestly when it is worth it.",
            highlights = listOf(
                TripHighlight(icon = "users", text = "Kids' clubs by age, nursery too"),
                TripHighlight(icon = "ship", text = "Castaway Cay private island"),
                TripHighlight(icon = "star", text = "Rotational dining with your servers"),
                TripHighlight(icon = "plane", text = "Sails from Port Canaveral"),
            ),
            sampleItinerary = listOf(
                "Day 1 · Board, sail-away party",
                "Day 2 · Sea day — shows and pool deck",
                "Day 3 · Cozumel",
                "Day 4 · Castaway Cay",
            ),
            line = "Disney",
        ),
        Trip(
            slug = "celebrity-edge",
            name = "Celebrity Edge",
            tagline = "Southern Caribbean · 11 nights · Curaçao + Aruba",
            overline = "CELEBRITY · ADULTS",
            type = TripType.CRUISE,
            vibes = listOf(
                Vibe.ADULTS_ONLY,
                Vibe.COUPLES,
                Vibe.FIVE_STAR,
            ),
            topics = mapOf(
                Topic.CRUISES to TopicPlacement(order = 3, overline = null, tagline = null, badge = null),
            ),
            destination = Destination(place = "Southern Caribbean from Fort Lauderdale", region = "Caribbean", island = null),
            nights = 11,
            band = PriceBand.THREE,
            from = Money(amountCents = 398000L, currency = "USD"),
            priceAsOf = "2026-09-02",
            pricePlaceholder = true,
            priceNote = "Illustrative starting price — request a quote for real prices on your dates.",
            badge = null,
            imageKey = "cruiseShip",
            heroImageKey = null,
            description = "A quieter, grown-up ship with real dining and a longer route into the southern Caribbean — Curaçao, Aruba, Bonaire. For couples who want the cruise without the waterslides.",
            highlights = listOf(
                TripHighlight(icon = "heart", text = "Grown-up pace, premium dining"),
                TripHighlight(icon = "ship", text = "Curaçao, Aruba, Bonaire"),
                TripHighlight(icon = "star", text = "Infinite Veranda staterooms"),
                TripHighlight(icon = "plane", text = "Sails from Fort Lauderdale"),
            ),
            sampleItinerary = listOf(
                "Day 1 · Board in Fort Lauderdale",
                "Day 2 · Sea day — rooftop garden and spa",
                "Day 3 · Sea day",
                "Day 4 · Aruba",
            ),
            line = "Celebrity",
        ),
        Trip(
            slug = "sky-princess",
            name = "Sky Princess",
            tagline = "Bahamas · 4 nights · Quick getaway",
            overline = "PRINCESS · WEEKEND",
            type = TripType.CRUISE,
            vibes = listOf(
                Vibe.COUPLES,
            ),
            topics = mapOf(
                Topic.CRUISES to TopicPlacement(order = 4, overline = null, tagline = null, badge = null),
            ),
            destination = Destination(place = "Bahamas from Fort Lauderdale", region = "Caribbean", island = null),
            nights = 4,
            band = PriceBand.ONE,
            from = Money(amountCents = 89000L, currency = "USD"),
            priceAsOf = "2026-09-02",
            pricePlaceholder = true,
            priceNote = "Illustrative starting price — request a quote for real prices on your dates.",
            badge = null,
            imageKey = "bahamas",
            heroImageKey = null,
            description = "Four nights, one long weekend, no vacation days to negotiate. A short Bahamas loop for couples who need a reset more than a big trip.",
            highlights = listOf(
                TripHighlight(icon = "clock", text = "Long-weekend length"),
                TripHighlight(icon = "ship", text = "Princess Cays beach day"),
                TripHighlight(icon = "utensils", text = "Meals included on board"),
                TripHighlight(icon = "plane", text = "Sails from Fort Lauderdale"),
            ),
            sampleItinerary = listOf(
                "Day 1 · Board Thursday afternoon",
                "Day 2 · Princess Cays",
                "Day 3 · Nassau",
                "Day 4 · Sea day, home Monday",
            ),
            line = "Princess",
        ),
        Trip(
            slug = "virgin-resilient-lady",
            name = "Virgin Resilient Lady",
            tagline = "Adults-only · 5 nights · Puerto Plata",
            overline = "VIRGIN · ADULTS",
            type = TripType.CRUISE,
            vibes = listOf(
                Vibe.ADULTS_ONLY,
                Vibe.COUPLES,
            ),
            topics = mapOf(
                Topic.CRUISES to TopicPlacement(order = 5, overline = null, tagline = null, badge = null),
            ),
            destination = Destination(place = "Dominican Republic from Miami", region = "Caribbean", island = null),
            nights = 5,
            band = PriceBand.TWO,
            from = Money(amountCents = 162000L, currency = "USD"),
            priceAsOf = "2026-09-02",
            pricePlaceholder = true,
            priceNote = "Illustrative starting price — request a quote for real prices on your dates.",
            badge = null,
            imageKey = "cruiseAerial",
            heroImageKey = null,
            description = "Adults only, no buffets, no formal nights, and a beach club in Bimini. Virgin's ships are for couples and friend groups who want the cruise energy without the kids' pool.",
            highlights = listOf(
                TripHighlight(icon = "heart", text = "Adults-only, no formal nights"),
                TripHighlight(icon = "utensils", text = "Restaurants instead of buffets"),
                TripHighlight(icon = "ship", text = "Beach Club at Bimini"),
                TripHighlight(icon = "plane", text = "Sails from Miami"),
            ),
            sampleItinerary = listOf(
                "Day 1 · Board in Miami",
                "Day 2 · Puerto Plata",
                "Day 3 · Sea day",
                "Day 4 · Beach Club at Bimini",
            ),
            line = "Virgin Voyages",
        ),
        Trip(
            slug = "carnival-celebration",
            name = "Carnival Celebration",
            tagline = "Eastern Caribbean · 6 nights · Family-priced",
            overline = "CARNIVAL · FAMILY",
            type = TripType.CRUISE,
            vibes = listOf(
                Vibe.FAMILY,
                Vibe.GROUP,
            ),
            topics = mapOf(
                Topic.CRUISES to TopicPlacement(order = 6, overline = null, tagline = null, badge = null),
            ),
            destination = Destination(place = "Eastern Caribbean from Miami", region = "Caribbean", island = null),
            nights = 6,
            band = PriceBand.ONE,
            from = Money(amountCents = 99000L, currency = "USD"),
            priceAsOf = "2026-09-02",
            pricePlaceholder = true,
            priceNote = "Illustrative starting price — request a quote for real prices on your dates.",
            badge = null,
            imageKey = "cruiseShip",
            heroImageKey = null,
            description = "The best-value big-ship week for a family: a roller coaster at sea, a huge waterpark deck, and prices that leave room for excursions. Gyasi's pick when the budget matters more than the brand.",
            highlights = listOf(
                TripHighlight(icon = "users", text = "Family-priced staterooms"),
                TripHighlight(icon = "star", text = "BOLT roller coaster at sea"),
                TripHighlight(icon = "ship", text = "Eastern Caribbean ports"),
                TripHighlight(icon = "plane", text = "Sails from Miami"),
            ),
            sampleItinerary = listOf(
                "Day 1 · Board in Miami",
                "Day 2 · Sea day — waterpark and the coaster",
                "Day 3 · Amber Cove",
                "Day 4 · St. Thomas",
            ),
            line = "Carnival",
        ),
        Trip(
            slug = "holland-america-eurodam",
            name = "Holland America Eurodam",
            tagline = "Panama Canal · 11 nights · Bucket-list",
            overline = "HAL · GROUP",
            type = TripType.CRUISE,
            vibes = listOf(
                Vibe.GROUP,
                Vibe.COUPLES,
            ),
            topics = mapOf(
                Topic.CRUISES to TopicPlacement(order = 7, overline = null, tagline = null, badge = null),
            ),
            destination = Destination(place = "Panama Canal from Fort Lauderdale", region = "Panama Canal", island = null),
            nights = 11,
            band = PriceBand.THREE,
            from = Money(amountCents = 379000L, currency = "USD"),
            priceAsOf = "2026-09-02",
            pricePlaceholder = true,
            priceNote = "Illustrative starting price — request a quote for real prices on your dates.",
            badge = null,
            imageKey = "cruiseAerial",
            heroImageKey = null,
            description = "A bucket-list route through the Panama Canal on a mid-size ship with a slower rhythm — lectures, live music, long dinners. The trip Gyasi plans for reunions and milestone birthdays.",
            highlights = listOf(
                TripHighlight(icon = "ship", text = "Full Panama Canal transit day"),
                TripHighlight(icon = "users", text = "Group rates and a coordinator"),
                TripHighlight(icon = "star", text = "Mid-size ship, unhurried pace"),
                TripHighlight(icon = "plane", text = "Sails from Fort Lauderdale"),
            ),
            sampleItinerary = listOf(
                "Day 1 · Board in Fort Lauderdale",
                "Day 2 · Half Moon Cay",
                "Day 3 · Sea day",
                "Day 4 · Cartagena",
            ),
            line = "Holland America",
        ),
        Trip(
            slug = "norwegian-encore",
            name = "Norwegian Encore",
            tagline = "Bermuda · 7 nights · Pink-sand beaches",
            overline = "NCL · FAMILY",
            type = TripType.CRUISE,
            vibes = listOf(
                Vibe.FAMILY,
            ),
            topics = mapOf(
                Topic.CRUISES to TopicPlacement(order = 8, overline = null, tagline = null, badge = null),
            ),
            destination = Destination(place = "Bermuda from New York", region = "Bermuda", island = null),
            nights = 7,
            band = PriceBand.TWO,
            from = Money(amountCents = 179000L, currency = "USD"),
            priceAsOf = "2026-09-02",
            pricePlaceholder = true,
            priceNote = "Illustrative starting price — request a quote for real prices on your dates.",
            badge = null,
            imageKey = "bahamas",
            heroImageKey = null,
            description = "Sail from New York, no flights needed, and spend the middle of the week docked in Bermuda with pink-sand beaches a short ferry away. A different kind of cruise week for East Coast families.",
            highlights = listOf(
                TripHighlight(icon = "plane", text = "Sails from New York — no flights"),
                TripHighlight(icon = "palm", text = "Two-plus days docked in Bermuda"),
                TripHighlight(icon = "users", text = "Go-karts and a laser-tag deck"),
                TripHighlight(icon = "utensils", text = "Freestyle dining, eat when you like"),
            ),
            sampleItinerary = listOf(
                "Day 1 · Board in Manhattan",
                "Day 2 · Sea day — race track and pool deck",
                "Day 3 · Sea day",
                "Day 4 · Bermuda, Horseshoe Bay beach",
            ),
            line = "Norwegian",
        ),
        Trip(
            slug = "wonder-of-the-seas",
            name = "Wonder of the Seas",
            tagline = "Western Caribbean · 7 nights · Mahogany Bay",
            overline = "ROYAL · FAMILY",
            type = TripType.CRUISE,
            vibes = listOf(
                Vibe.FAMILY,
                Vibe.GROUP,
            ),
            topics = mapOf(
                Topic.CRUISES to TopicPlacement(order = 9, overline = null, tagline = null, badge = null),
            ),
            destination = Destination(place = "Western Caribbean from Port Canaveral", region = "Caribbean", island = null),
            nights = 7,
            band = PriceBand.TWO,
            from = Money(amountCents = 199000L, currency = "USD"),
            priceAsOf = "2026-09-02",
            pricePlaceholder = true,
            priceNote = "Illustrative starting price — request a quote for real prices on your dates.",
            badge = null,
            imageKey = "cruiseShip",
            heroImageKey = null,
            description = "Royal Caribbean's family flagship on the western loop — Roatán's Mahogany Bay, Costa Maya, Cozumel — with a suite neighborhood that makes a big group feel like it has its own corner of the ship.",
            highlights = listOf(
                TripHighlight(icon = "users", text = "Suite neighborhood for big groups"),
                TripHighlight(icon = "ship", text = "Mahogany Bay, Costa Maya, Cozumel"),
                TripHighlight(icon = "star", text = "Waterslides, ice rink, surf simulator"),
                TripHighlight(icon = "plane", text = "Sails from Port Canaveral"),
            ),
            sampleItinerary = listOf(
                "Day 1 · Board in Port Canaveral",
                "Day 2 · Perfect Day at CocoCay",
                "Day 3 · Sea day",
                "Day 4 · Roatán, Mahogany Bay",
            ),
            line = "Royal Caribbean",
        ),
        Trip(
            slug = "couples-sans-souci",
            name = "Couples Sans Souci",
            tagline = "Ocho Rios, Jamaica · Cliffside · 7 nights",
            overline = "BOUTIQUE · ADULTS",
            type = TripType.ALL_INCLUSIVE,
            vibes = listOf(
                Vibe.ADULTS_ONLY,
                Vibe.COUPLES,
                Vibe.HONEYMOON,
                Vibe.BOUTIQUE,
            ),
            topics = mapOf(
                Topic.HONEYMOONS to TopicPlacement(order = 2, overline = null, tagline = null, badge = null),
            ),
            destination = Destination(place = "Ocho Rios, Jamaica", region = "Caribbean", island = "jamaica"),
            nights = 7,
            band = PriceBand.TWO,
            from = Money(amountCents = 259000L, currency = "USD"),
            priceAsOf = "2026-09-02",
            pricePlaceholder = true,
            priceNote = "Illustrative starting price — request a quote for real prices on your dates.",
            badge = null,
            imageKey = "jamaica",
            heroImageKey = null,
            description = "Built into a hillside above two coves, with a natural mineral spring pool and a quieter, older-Jamaica feel. A honeymoon resort for couples who want charm over scale.",
            highlights = listOf(
                TripHighlight(icon = "heart", text = "Cliffside suites over two coves"),
                TripHighlight(icon = "star", text = "Mineral spring pool"),
                TripHighlight(icon = "utensils", text = "All dining, drinks and excursions included"),
                TripHighlight(icon = "plane", text = "About 90 minutes from Montego Bay"),
            ),
            sampleItinerary = listOf(
                "Day 1 · Arrive, first dinner above the cove",
                "Day 2 · Mineral pool morning, beach afternoon",
                "Day 3 · Dunn's River Falls",
                "Day 4 · Spa day for two",
            ),
            line = null,
        ),
        Trip(
            slug = "excellence-playa-mujeres",
            name = "Excellence Playa Mujeres",
            tagline = "Cancún · Adults-only · Beachfront swim-up",
            overline = "ALL-INCLUSIVE",
            type = TripType.ALL_INCLUSIVE,
            vibes = listOf(
                Vibe.ADULTS_ONLY,
                Vibe.COUPLES,
                Vibe.HONEYMOON,
            ),
            topics = mapOf(
                Topic.HONEYMOONS to TopicPlacement(order = 3, overline = null, tagline = null, badge = null),
            ),
            destination = Destination(place = "Playa Mujeres, Cancún, Mexico", region = "Mexico", island = null),
            nights = 7,
            band = PriceBand.TWO,
            from = Money(amountCents = 229000L, currency = "USD"),
            priceAsOf = "2026-09-02",
            pricePlaceholder = true,
            priceNote = "Illustrative starting price — request a quote for real prices on your dates.",
            badge = null,
            imageKey = "aruba",
            heroImageKey = null,
            description = "North of the Cancún hotel zone, on a calmer beach, with swim-up suites and a long list of restaurants. The best-value honeymoon all-inclusive Gyasi plans outside the Caribbean.",
            highlights = listOf(
                TripHighlight(icon = "heart", text = "Swim-up suites, adults-only"),
                TripHighlight(icon = "palm", text = "Quiet beach away from the hotel zone"),
                TripHighlight(icon = "utensils", text = "Ten-plus restaurants included"),
                TripHighlight(icon = "plane", text = "Short transfer from Cancún airport"),
            ),
            sampleItinerary = listOf(
                "Day 1 · Arrive, swim-up pool before dinner",
                "Day 2 · Beach day",
                "Day 3 · Isla Mujeres by ferry",
                "Day 4 · Spa and a slow dinner",
            ),
            line = null,
        ),
        Trip(
            slug = "le-blanc-spa-resort",
            name = "Le Blanc Spa Resort",
            tagline = "Cancún · Five-star · Couples-focused",
            overline = "LUXURY · ADULTS",
            type = TripType.ALL_INCLUSIVE,
            vibes = listOf(
                Vibe.ADULTS_ONLY,
                Vibe.COUPLES,
                Vibe.HONEYMOON,
                Vibe.FIVE_STAR,
            ),
            topics = mapOf(
                Topic.HONEYMOONS to TopicPlacement(order = 4, overline = null, tagline = null, badge = null),
            ),
            destination = Destination(place = "Cancún, Mexico", region = "Mexico", island = null),
            nights = 7,
            band = PriceBand.THREE,
            from = Money(amountCents = 412000L, currency = "USD"),
            priceAsOf = "2026-09-02",
            pricePlaceholder = true,
            priceNote = "Illustrative starting price — request a quote for real prices on your dates.",
            badge = null,
            imageKey = "overwater",
            heroImageKey = null,
            description = "The five-star, butler-service, spa-first honeymoon. Everything is included and everything is quiet. For the couple who wants one week of being completely looked after.",
            highlights = listOf(
                TripHighlight(icon = "star", text = "Butler service, five-star throughout"),
                TripHighlight(icon = "heart", text = "Spa-focused, adults-only"),
                TripHighlight(icon = "utensils", text = "Fine dining included"),
                TripHighlight(icon = "plane", text = "Twenty minutes from Cancún airport"),
            ),
            sampleItinerary = listOf(
                "Day 1 · Arrive, unpacked for you, dinner on the terrace",
                "Day 2 · Spa morning, beach afternoon",
                "Day 3 · Private Chichén Itzá day (optional)",
                "Day 4 · Nothing planned — on purpose",
            ),
            line = null,
        ),
        Trip(
            slug = "hamanasi-resort",
            name = "Hamanasi Resort",
            tagline = "Belize · Adventure + beach hybrid",
            overline = "ADVENTURE",
            type = TripType.HOTEL,
            vibes = listOf(
                Vibe.ADVENTURE,
                Vibe.COUPLES,
                Vibe.HONEYMOON,
                Vibe.BOUTIQUE,
            ),
            topics = mapOf(
                Topic.HONEYMOONS to TopicPlacement(order = 5, overline = null, tagline = null, badge = "Off-the-beaten"),
            ),
            destination = Destination(place = "Hopkins, Belize", region = "Belize", island = null),
            nights = 7,
            band = PriceBand.TWO,
            from = Money(amountCents = 289000L, currency = "USD"),
            priceAsOf = "2026-09-02",
            pricePlaceholder = true,
            priceNote = "Illustrative starting price — request a quote for real prices on your dates.",
            badge = "Off-the-beaten",
            imageKey = "snorkel",
            heroImageKey = null,
            description = "Half beach, half jungle: a small eco-resort on the Belize coast with guided reef dives one day and Mayan ruins the next. For couples who would rather earn their rest than lie down for it.",
            highlights = listOf(
                TripHighlight(icon = "star", text = "Belize Barrier Reef dives and snorkels"),
                TripHighlight(icon = "palm", text = "Jungle treehouses and beach rooms"),
                TripHighlight(icon = "map", text = "Guided ruins and river trips"),
                TripHighlight(icon = "utensils", text = "Meals and adventures bundled"),
            ),
            sampleItinerary = listOf(
                "Day 1 · Arrive, beach dinner",
                "Day 2 · Reef snorkel or dive",
                "Day 3 · Mayan ruins and cave river",
                "Day 4 · Hammock day",
            ),
            line = null,
        ),
    )

    val ISLANDS: List<Island> = listOf(
        Island(slug = "turks-and-caicos", name = "Turks & Caicos", imageKey = "turks"),
        Island(slug = "bahamas", name = "Bahamas", imageKey = "bahamas"),
        Island(slug = "st-lucia", name = "St. Lucia", imageKey = "stlucia"),
        Island(slug = "jamaica", name = "Jamaica", imageKey = "jamaica"),
        Island(slug = "aruba", name = "Aruba", imageKey = "aruba"),
        Island(slug = "bvi", name = "BVI", imageKey = "bvi"),
    )

    val CRUISE_LINES: List<CruiseLine> = listOf(
        CruiseLine(slug = "royal-caribbean", name = "Royal Caribbean"),
        CruiseLine(slug = "celebrity", name = "Celebrity"),
        CruiseLine(slug = "disney", name = "Disney"),
        CruiseLine(slug = "princess", name = "Princess"),
        CruiseLine(slug = "carnival", name = "Carnival"),
        CruiseLine(slug = "virgin-voyages", name = "Virgin Voyages"),
        CruiseLine(slug = "norwegian", name = "Norwegian"),
        CruiseLine(slug = "holland-america", name = "Holland America"),
    )

    val INSPIRATION_TILES: List<InspirationTile> = listOf(
        InspirationTile(
            slug = "caribbean-escapes",
            title = "Caribbean escapes",
            imageKey = "turks",
            query = InspirationQuery(topic = Topic.CARIBBEAN, type = null, vibe = null, dest = null),
        ),
        InspirationTile(
            slug = "family-cruises",
            title = "Family cruises",
            imageKey = "cruiseShip",
            query = InspirationQuery(topic = null, type = TripType.CRUISE, vibe = Vibe.FAMILY, dest = null),
        ),
        InspirationTile(
            slug = "honeymoons",
            title = "Honeymoons",
            imageKey = "honeymoon",
            query = InspirationQuery(topic = Topic.HONEYMOONS, type = null, vibe = null, dest = null),
        ),
        InspirationTile(
            slug = "all-inclusive-resorts",
            title = "All-inclusive resorts",
            imageKey = "resortPool",
            query = InspirationQuery(topic = null, type = TripType.ALL_INCLUSIVE, vibe = null, dest = null),
        ),
        InspirationTile(
            slug = "adventure-travel",
            title = "Adventure travel",
            imageKey = "snorkel",
            query = InspirationQuery(topic = null, type = null, vibe = Vibe.ADVENTURE, dest = null),
        ),
        InspirationTile(
            slug = "group-trips",
            title = "Group trips · 6+",
            imageKey = "overwater",
            query = InspirationQuery(topic = null, type = null, vibe = Vibe.GROUP, dest = null),
        ),
    )

    val HOW_IT_WORKS_FAQ: List<FaqItem> = listOf(
        FaqItem(q = "Do I pay a planning fee?", a = "No. Inteletravel host-agency policy prohibits it. Gyasi earns commission from suppliers — you pay them, never us."),
        FaqItem(q = "What does Inteletravel mean for me?", a = "It's the host agency that issues bookings. You'll see them on supplier invoices. It does not change how you work with Story-Tail."),
        FaqItem(q = "How does payment authorization work?", a = "You add a card through a Stripe-secured form. Story-Tail uses it only to pay suppliers on your behalf — never to charge you a service fee. Every use is audit-logged and you get notified."),
        FaqItem(q = "Can I plan without an account?", a = "You can browse and inquire as a guest. To save searches, view a real proposal, or authorize a card, you'll create an account."),
    )

    val GYASI_FAQ: List<FaqItem> = listOf(
        FaqItem(q = "Do you charge a planning fee?", a = "No — and I can't. As an Inteletravel-hosted advisor I'm contractually prohibited from charging clients planning, consultation, or service fees. I earn commission from suppliers when you travel."),
        FaqItem(q = "What if I just want to message you, no commitment?", a = "Please do. Most relationships start with a casual question. Use the \"Message Gyasi\" link on any page — no account needed."),
        FaqItem(q = "Why the Caribbean specifically?", a = "I lived in the islands. I know which Sandals has the best Red Lane spa (Grande St. Lucian). I know which Royal Caribbean ship to put a multi-gen family on (Wonder, hands down). When you know one region well, you serve people better."),
        FaqItem(q = "Do you book non-Caribbean trips?", a = "Yes — Mexico, Europe, cruises anywhere, group trips, all-inclusives worldwide. The Caribbean is my deepest specialty, not my only one."),
        FaqItem(q = "How does payment work?", a = "You add a card through a Stripe-secured form. I use it only to pay suppliers on your behalf, up to a cap you authorize, with audit logs and notifications. I never charge you a service fee."),
    )

    val LEGAL_DOCS: List<LegalDoc> = listOf(
        LegalDoc(
            slug = LegalSlug.PRIVACY,
            title = "Privacy policy",
            navLabel = "Privacy",
            description = "What Story-Tail Adventures collects, how payment cards are handled, and your data rights.",
            lastUpdated = "2026-09-02",
            status = "draft",
            sections = listOf(
            LegalSection(
                heading = "1. What we collect",
                paragraphs = listOf(
                    "Story-Tail Adventures collects contact information, trip details, travel preferences, and travel-document details you choose to share, only to plan and support your trips. Payment cards are collected through Stripe and stored as tokens; we keep the card brand, last four digits and expiration so you can recognize a card, never the full number.",
                    "We do not sell your information, and we do not share it with marketing third parties.",
                ),
                bullets = emptyList(),
            ),
            LegalSection(
                heading = "2. How payment cards are handled",
                paragraphs = listOf(
                    "Cards you add through the portal are tokenized by Stripe before they leave your browser. The full card number is stored only by Stripe. Story-Tail uses your card only to pay travel suppliers on your behalf, up to the limit you authorize for a trip — never to charge you a planning, consultation or service fee.",
                    "Most suppliers are paid directly through Stripe. A few suppliers can only accept payment by hand. For those, your advisor can view a card number through a time-limited, audited step that requires a second sign-in factor; every view is recorded and you are notified. You can revoke a stored card at any time.",
                ),
                bullets = emptyList(),
            ),
            LegalSection(
                heading = "3. Who we share it with",
                paragraphs = listOf(
                    "Trip details and traveler names go to the suppliers who deliver your trip (airlines, resorts, cruise lines, tour operators) and to Inteletravel, the host agency that issues bookings. Payment processing is handled by Stripe. Our hosting and database providers process data on our behalf under contract.",
                ),
                bullets = emptyList(),
            ),
            LegalSection(
                heading = "4. Your data rights",
                paragraphs = listOf(
                    "You can ask for a copy of the personal data we hold about you, ask us to correct it, or ask us to close your account. Account closure preserves booking and payment records for tax and compliance reasons but anonymizes your personal identifiers. Email us and we will respond within 30 days.",
                ),
                bullets = emptyList(),
            ),
            LegalSection(
                heading = "5. Retention and security",
                paragraphs = listOf(
                    "We keep trip and payment records for as long as tax and host-agency rules require, and delete or anonymize the rest when you close your account. Access to sensitive data is logged, and every payment-card action generates an audit record.",
                ),
                bullets = emptyList(),
            ),
            LegalSection(
                heading = "6. Contact",
                paragraphs = listOf(
                    "Questions about this policy or your data: use the “Message Gyasi” link on any page.",
                ),
                bullets = emptyList(),
            ),
            ),
        ),
        LegalDoc(
            slug = LegalSlug.TERMS,
            title = "Terms of service",
            navLabel = "Terms",
            description = "How the Story-Tail Adventures portal works, what we do and don't charge for, and what you agree to when you use it.",
            lastUpdated = "2026-09-02",
            status = "draft",
            sections = listOf(
            LegalSection(
                heading = "1. Who we are",
                paragraphs = listOf(
                    "Story-Tail Adventures is an independent travel advisory business hosted by Inteletravel. Your bookings are issued through Inteletravel and fulfilled by the travel suppliers named on your itinerary. This portal is where you view trips, message your advisor, and authorize payment cards for those suppliers.",
                ),
                bullets = emptyList(),
            ),
            LegalSection(
                heading = "2. No planning fees",
                paragraphs = listOf(
                    "Story-Tail Adventures does not charge planning, consultation or service fees, and our host-agency agreement prohibits it. We earn commission from suppliers when you travel. Prices shown in the portal come from suppliers; supplier terms, deposits and cancellation rules apply to each booking.",
                ),
                bullets = emptyList(),
            ),
            LegalSection(
                heading = "3. Payment authorization",
                paragraphs = listOf(
                    "When you authorize a card for a trip, you set the limit and the suppliers it may be used for. Story-Tail uses it only to pay those suppliers, within that limit, and every use is recorded and reported to you. You can revoke an authorization at any time; charges already made by a supplier are governed by that supplier's terms.",
                ),
                bullets = emptyList(),
            ),
            LegalSection(
                heading = "4. Your account",
                paragraphs = listOf(
                    "Keep your sign-in details private and let us know if you think someone else has used your account. You are responsible for the accuracy of traveler names, dates of birth and travel-document details you provide; airlines and border authorities require them to match your documents exactly.",
                ),
                bullets = emptyList(),
            ),
            LegalSection(
                heading = "5. Illustrative content",
                paragraphs = listOf(
                    "Trip ideas, sample itineraries and starting prices on the public pages are illustrative and change with season, availability and supplier pricing. A quote from your advisor is the only price that binds.",
                ),
                bullets = emptyList(),
            ),
            LegalSection(
                heading = "6. Changes to these terms",
                paragraphs = listOf(
                    "We may update these terms as the portal grows. We will note the date at the top of this page and, for material changes, tell you in the portal or by email.",
                ),
                bullets = emptyList(),
            ),
            ),
        ),
        LegalDoc(
            slug = LegalSlug.COOKIES,
            title = "Cookies",
            navLabel = "Cookies",
            description = "The small number of cookies and browser storage keys the Story-Tail portal uses, and what each one does.",
            lastUpdated = "2026-09-02",
            status = "draft",
            sections = listOf(
            LegalSection(
                heading = "1. What we use",
                paragraphs = listOf(
                    "The portal uses cookies only to keep you signed in and to remember a few preferences. We do not use advertising cookies or third-party trackers on the app subdomain.",
                ),
                bullets = listOf(
                    "Sign-in session cookies (set by our authentication provider, Supabase) so you stay signed in between pages.",
                    "A light-or-dark appearance preference, stored in your browser's local storage.",
                    "A note that you dismissed the “sign in to save” banner on the search pages, stored in local storage.",
                ),
            ),
            LegalSection(
                heading = "2. Payment forms",
                paragraphs = listOf(
                    "When you add a card, the form is served by Stripe and may set Stripe's own cookies to prevent fraud. Those are governed by Stripe's privacy policy.",
                ),
                bullets = emptyList(),
            ),
            LegalSection(
                heading = "3. Your choices",
                paragraphs = listOf(
                    "You can clear cookies and local storage in your browser at any time. Clearing the session cookie signs you out; the portal keeps working for browsing without an account.",
                ),
                bullets = emptyList(),
            ),
            ),
        ),
        LegalDoc(
            slug = LegalSlug.ACCESSIBILITY,
            title = "Accessibility statement",
            navLabel = "Accessibility",
            description = "How the Story-Tail portal is built to be usable by everyone, what we know still falls short, and how to tell us.",
            lastUpdated = "2026-09-02",
            status = "draft",
            sections = listOf(
            LegalSection(
                heading = "1. Our commitment",
                paragraphs = listOf(
                    "Rest is for everyone, and so is this portal. We build to the Web Content Accessibility Guidelines (WCAG) 2.2 at level AA: semantic headings and landmarks, visible focus, keyboard access to every control, text alternatives for images that carry meaning, and layouts that reflow on small screens and at 200% zoom.",
                ),
                bullets = emptyList(),
            ),
            LegalSection(
                heading = "2. What works today",
                paragraphs = emptyList(),
                bullets = listOf(
                    "Every page has one main heading and a skip-to-content link.",
                    "Menus, filters and forms work with a keyboard and screen reader; the mobile menu traps focus and closes with Escape.",
                    "Light and dark appearance follow your device or your choice.",
                    "Animations respect the “reduce motion” setting.",
                    "Legal pages print cleanly in a light palette.",
                ),
            ),
            LegalSection(
                heading = "3. Known limitations",
                paragraphs = listOf(
                    "Two brand colour pairs measure below the AA contrast ratio for small text: orange section labels on the cream background, and white text on orange buttons. Both are legible at their sizes but we are working with the designer on adjustments.",
                    "Hero photographs carry decorative text overlays; the same information is always available as plain text on the page.",
                ),
                bullets = emptyList(),
            ),
            LegalSection(
                heading = "4. Tell us",
                paragraphs = listOf(
                    "If something is hard to use, use the “Message Gyasi” link on any page and describe what happened and what you were trying to do. We will fix what we can quickly and tell you when we have.",
                ),
                bullets = emptyList(),
            ),
            ),
        ),
    )

    val CLAIMS: List<Claim> = listOf(
        Claim(id = "travelersServed", display = "240+", detail = "Travelers served", verified = false),
        Claim(id = "ratingValue", display = "4.9", detail = "Average rating", verified = false),
        Claim(id = "reviewCount", display = "138", detail = "Reviews", verified = false),
        Claim(id = "avgReplyTime", display = "< 2h", detail = "Avg reply time", verified = false),
        Claim(id = "yearsSpecialist", display = "5 yrs", detail = "Caribbean specialist", verified = false),
        Claim(id = "credInteletravel", display = "Hosted by Inteletravel", detail = "IATA-accredited host agency · Full supplier access", verified = false),
        Claim(id = "credClia", display = "CLIA Member", detail = "Cruise Lines International Association · Sailings booked yearly", verified = false),
        Claim(id = "credSandals", display = "Sandals Certified Specialist", detail = "Trained on all properties in Jamaica, Bahamas, St. Lucia, Turks", verified = false),
        Claim(id = "credRoyal", display = "Royal Caribbean Master", detail = "Master-level certification · Symphony, Wonder, Icon class", verified = false),
        Claim(id = "bioParent", display = "dad of three", detail = null, verified = false),
        Claim(id = "bioIslands", display = "I lived in the islands.", detail = null, verified = false),
        Claim(id = "bioStarted", display = "2019", detail = "Started planning trips for friends", verified = false),
        Claim(id = "bioNamed", display = "2021", detail = "Story-Tail Adventures got its name", verified = false),
        Claim(id = "plannedRoyalBahamian", display = "14", detail = "Sandals Royal Bahamian trips planned", verified = false),
        Claim(id = "catalogUpdatedMonthly", display = "Updated monthly.", detail = null, verified = false),
        Claim(id = "sailsEachLineYearly", display = "I sail with each line at least once a year, so the recommendation isn't a brochure — it's lived.", detail = null, verified = false),
        Claim(id = "replyWithin48h", display = "within 48 hours", detail = null, verified = false),
        Claim(id = "islandsPlannedAll", display = "Twelve islands. One advisor who's planned every one of them.", detail = null, verified = false),
        Claim(id = "tripDetails", display = "Trip descriptions, highlights and sample itineraries", detail = "Drafted from the design prototype and public supplier information; confirm with suppliers.", verified = false),
    )

    val TESTIMONIALS: List<Testimonial> = listOf(
        Testimonial(quote = "Gyasi planned our first family cruise. Three kids, two grandparents, one mom who needed a break. He didn't miss a detail — even called when our connection got cancelled in Miami.", who = "The Westbrook Family", trip = "Symphony · Dec 2024", initials = "WF", consented = false),
        Testimonial(quote = "He steered us to a quieter resort than what we picked online — saved us thousands too. Best honeymoon week we could've asked for.", who = "Reggie & Marc", trip = "Sandals St. Lucia · May 2024", initials = "RM", consented = false),
        Testimonial(quote = "I message him at 9pm with random questions and he replies. That's the whole pitch right there — he actually cares.", who = "Aisha Patel", trip = "Atlantis · Mar 2024", initials = "AP", consented = false),
        Testimonial(quote = "We did a multi-gen group trip — 12 people, two cabins, three flights from three cities. He made it feel small.", who = "The Khan Family", trip = "Beaches T&C · Aug 2024", initials = "KF", consented = false),
        Testimonial(quote = "No high-pressure sales, no upselling. Just real options, real prices, and a person who picks up the phone.", who = "Tasha Whitfield", trip = "Aruba · Oct 2023", initials = "TW", consented = false),
        Testimonial(quote = "I was nervous about authorizing a card online. He walked me through every step, sent me the audit log, never made me feel silly.", who = "Linda Gomez", trip = "Riviera Maya · Jan 2024", initials = "LG", consented = false),
    )

    /** The design's photography registry. None of it is licensed yet — see PublicPhoto. */
    val IMAGES: List<RegisteredImage> = listOf(
        RegisteredImage(key = "turks", alt = "Turquoise water and white sand on a Turks and Caicos beach", licensed = false),
        RegisteredImage(key = "bahamas", alt = "Palm trees along a boardwalk to the beach at Nassau, The Bahamas", licensed = false),
        RegisteredImage(key = "stlucia", alt = "The Pitons rising from the sea in St. Lucia", licensed = false),
        RegisteredImage(key = "jamaica", alt = "Cliffs above clear turquoise water", licensed = false),
        RegisteredImage(key = "aruba", alt = "Thatched palapas on the palm-lined sand at Arashi Beach, Aruba", licensed = false),
        RegisteredImage(key = "bvi", alt = "A catamaran under sail on turquoise water", licensed = false),
        RegisteredImage(key = "resortPool", alt = "Infinity pool at a beachfront resort", licensed = false),
        RegisteredImage(key = "overwater", alt = "Overwater bungalows above a calm lagoon", licensed = false),
        RegisteredImage(key = "resortNight", alt = "Resort lit up at night", licensed = false),
        RegisteredImage(key = "cruiseShip", alt = "Cruise ship at sea", licensed = false),
        RegisteredImage(key = "cruiseAerial", alt = "Cruise ship seen from above", licensed = false),
        RegisteredImage(key = "honeymoon", alt = "Couple walking along a beach at golden hour", licensed = false),
        RegisteredImage(key = "candlelit", alt = "A long table set with candles and flowers for dinner", licensed = false),
        RegisteredImage(key = "family", alt = "Water slides above a resort pool", licensed = false),
        RegisteredImage(key = "zipline", alt = "A zipline rider crossing a rainforest canopy", licensed = false),
        RegisteredImage(key = "snorkel", alt = "Snorkeler over a coral reef", licensed = false),
        RegisteredImage(key = "palmTree", alt = "Palm tree over a tropical beach", licensed = false),
        RegisteredImage(key = "sunset", alt = "Palm silhouettes against a tropical sunset", licensed = false),
    )
}
