// The brand mark — see docs/Design-System.md §11 (Logo Usage). The Compose counterpart
// of web/components/brand/BrandMark.tsx; both read drawables generated by
// web/scripts/build-brand-assets.mts. P1.
package com.storytail.adventures.ui.components

import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.height
import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import com.storytail.adventures.shared.resources.Res
import com.storytail.adventures.shared.resources.lockup_dark
import com.storytail.adventures.shared.resources.lockup_light
import org.jetbrains.compose.resources.painterResource

/** Which artwork the surface behind the mark calls for. */
enum class BrandTone {
    /** Follow the active colour scheme. */
    Auto,

    /** The surface is always light, whatever the scheme — the book-and-fox lockup. */
    Light,

    /** The surface is always dark, whatever the scheme — the tropical lockup. */
    Dark,
}

/**
 * The Story-Tail Adventures logo — the real artwork, one lockup per colour scheme.
 *
 *   light  the horizontal book-and-fox lockup, 2.52:1
 *   dark   the stacked palm-and-sunset lockup, 0.986:1
 *
 * This replaces the wordmark-only placeholder that stood here while the brand assets were
 * unexported. The two lockups are different compositions rather than two colourways of one
 * drawing, so the mark changes shape with the scheme: at a given height the light one is a
 * wide banner and the dark one a compact badge.
 *
 * Both drawables are generated by web/scripts/build-brand-assets.mts from the masters in
 * design/source-prototype/brand/, so web and mobile cannot drift.
 *
 * [size] is the rendered height; the width follows from each lockup's own aspect. Do not go
 * below 80.dp — the light lockup's "ADVENTURES" line is 8.8% of its height, so below that it
 * stops being readable.
 */
@Composable
fun BrandMark(
    size: Dp = 80.dp,
    tone: BrandTone = BrandTone.Auto,
    contentDescription: String? = "Story-Tail Adventures",
    modifier: Modifier = Modifier,
) {
    // Read the scheme off the background rather than isSystemInDarkTheme(): StoryTailTheme
    // takes useDarkTheme as a parameter, so a caller that overrides it would otherwise get
    // the wrong lockup on a correctly-themed surface.
    val dark = when (tone) {
        BrandTone.Auto -> MaterialTheme.colorScheme.background.luminanceIsDark()
        BrandTone.Dark -> true
        BrandTone.Light -> false
    }

    Image(
        painter = painterResource(if (dark) Res.drawable.lockup_dark else Res.drawable.lockup_light),
        contentDescription = contentDescription,
        modifier = modifier.height(size),
        contentScale = ContentScale.Fit,
    )
}

/** Cheap perceptual-luminance check, so the mark tracks whatever the surface actually is. */
private fun Color.luminanceIsDark(): Boolean =
    (0.299f * red + 0.587f * green + 0.114f * blue) < 0.5f
