/**
 * Static image imports (`import logo from "./logo.webp"`) typed as `StaticImageData`.
 *
 * Next ships these declarations in `next/image-types/global`, and `next-env.d.ts` already
 * references them — but that file is generated by `next dev` / `next build` and is
 * gitignored (web/.gitignore). CI runs `typecheck` before `build`, so on a fresh checkout
 * it does not exist yet and every static image import fails with TS2307.
 *
 * Nothing caught this until components/brand/BrandMark.tsx, which is the first static
 * image import in the app. Referencing the types from a committed file makes the build
 * order irrelevant. Re-referencing what next-env.d.ts also pulls in is harmless: a
 * `/// <reference types="…" />` for an already-loaded package is a no-op, not a
 * redeclaration, which a second `declare module "*.webp"` here would have been.
 */

/// <reference types="next/image-types/global" />
