/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/hotel-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Live hotel search for the public Explore surface.
         * @description Screen 2.0.4 in Hotels mode, and 2.3.3 later. Calls SerpApi's Google Hotels engine
         *     for the dates given and returns normalised hotel content plus ONE indicative
         *     nightly rate per property.
         *
         *     NOT CALLED FROM A BROWSER. The caller is the Next.js server
         *     (`web/lib/public/hotels.ts`), presenting the project anon key plus the server-only
         *     `X-STA-Search-Token`. `verify_jwt` stays true and there is no anon RLS policy
         *     anywhere: this function is the boundary, not a table. The anon key is public — it
         *     ships in the browser bundle — so it authenticates nobody, which is what the header
         *     is for.
         *
         *     THE RESPONSE CARRIES NO BOOKING-SITE IDENTITY. The provider's
         *     `properties[].prices[]` — site names, their logos, their links — is dropped at the
         *     mapper and has no field to land in here. Free-Travel-APIs §1.3.5 forbids promoting
         *     another business on this site; §10.2 asks for that to be structural rather than
         *     remembered. See `HotelRate`, which is one scalar rather than a list, for why.
         *
         *     DEGRADATION IS A 200. When the monthly budget is spent the response carries
         *     `degraded: "budget_exhausted"` with empty `results`, and the page falls back to the
         *     curated catalog. Late in a month on the free tier that is the expected outcome, not
         *     a failure. `source: "stale"` means the budget is spent but a recent expired cache
         *     entry was served — `staleAsOf` says how old, and the page must say so.
         *
         *     POST rather than GET so the filter arrays cannot be serialised two ways by two
         *     callers, which is the cache-key hazard the whole design is built around.
         */
        post: operations["searchHotels"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trip-message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post a message into a trip thread.
         * @description Screen 2.2.7. `message` has SELECT-only RLS and no write policy, so a PostgREST
         *     insert would match zero rows and return 204 — looking like it worked and changing
         *     nothing. The function resolves the conversation from the trip, refuses if the
         *     caller does not own it, writes the message and any attachment rows in one
         *     transaction, and writes an `audit_event` (CLAUDE.md rule 3).
         */
        post: operations["sendTripMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trip-document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a document and get a short-lived upload URL for it.
         * @description Screens 2.2.6 and 2.2.11. Two things have to happen together: a `document` row has
         *     to exist, and an object has to land in the private `trip-documents` bucket. The
         *     client can do neither directly — it has no write policy on `document` and is never
         *     granted `storage_key` — so the function creates the row, signs an upload URL for a
         *     key the client never chooses, and audits it.
         *
         *     `kind` is constrained to the kinds a client may contribute. A client cannot create
         *     a `receipt` or a `csv_import`: those are agency records, and the read policy
         *     excludes them for the same reason.
         */
        post: operations["requestTripDocumentUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trip-document-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sign a short-lived read URL for a document the caller owns.
         * @description The single door to the `trip-documents` bucket, and the reason the bucket has no
         *     `authenticated` policies at all: `document.storage_bucket` and `storage_key` are
         *     outside the client column grant, so a client can never name an object and could
         *     never reach a storage policy even if one existed.
         *
         *     This is not a web-only convenience. A Compose Multiplatform app has no server, so
         *     without this endpoint Screens 2.2.6 and 2.2.11 cannot open a file on Android or iOS
         *     at all.
         *
         *     Ownership is re-checked against the same predicate `document_self_select` uses,
         *     including the `kind` allowlist, and every signature is written to `audit_event`.
         */
        get: operations["getTripDocumentUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/testimonial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save or submit a reflection on a trip.
         * @description Screen 2.2.11. `testimonial` has no client write policy because a direct insert
         *     would carry no `audit_event`, and because the draft-to-submitted transition needs
         *     validating somewhere the client cannot reach.
         *
         *     A client may only ever reach `draft` and `submitted`. Approval and publication are
         *     agent actions and land with §3.x — the CHECK constraints on the table enforce that
         *     nothing is published without an approval, so a bug here fails loudly.
         */
        post: operations["saveTestimonial"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding-step": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move the wizard cursor, or mark onboarding complete.
         * @description Screens 2.1.9 – 2.1.14. Writes `platform_user.onboarding_step`, or
         *     `onboarding_completed_at` when `complete` is true.
         *
         *     Send EITHER a known `step` OR `complete: true`. Anything else is a 400 —
         *     an unrecognised step would silently strand somebody mid-wizard.
         */
        post: operations["setOnboardingStep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save the traveler's own details. Screen 2.1.10.
         * @description Writes `client` (phone, date of birth, emergency contact), `address` and
         *     the traveler's own `travel_document` row. Audited as `client.updated`.
         *
         *     THE PASSPORT NUMBER IS NOT ACCEPTED. `travel_document.document_number_encrypted`
         *     is Sensitive PII that Data-Model §18.2 requires be encrypted under a
         *     backend-held DEK, and none of that is built — collecting a number in
         *     order to store it unprotected is worse than not collecting it. Sending
         *     `passport.number` is a 400 rather than being ignored, so a caller learns
         *     it was not stored instead of discovering later that it never was.
         *
         *     The mailing address is six structured fields, not one line: there is no
         *     free-text address column anywhere in the schema, and `line1`, `city` and
         *     `country` are NOT NULL together or absent together.
         */
        post: operations["saveOnboardingProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding-preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save travel preferences. Screen 2.1.11.
         * @description Writes one `travel_preference` row per client. Every list is validated
         *     against the vocabulary in Data-Model §6.2; a value outside it is a 400.
         *
         *     `dietary` and `accessibility` treat `none` as EXCLUSIVE — "none" plus
         *     something else is a contradiction and is refused rather than silently
         *     resolved.
         *
         *     The budget is one of four bands, not a number. Two slider thumbs would
         *     be two numbers plus a currency (CLAUDE.md rule 5) to capture a figure
         *     the traveler is guessing at, and the bands match `lead.budget_band` so a
         *     Phase 2 lead converts without translation.
         */
        post: operations["saveOnboardingPreferences"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding-companions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add, edit or remove a travel companion. Screen 2.1.12.
         * @description One companion per call, chosen by `action`. `none` writes nothing and
         *     exists so "Save & continue" with an already-complete list can advance
         *     the cursor without inventing a row.
         *
         *     `remove` is a soft delete. A companion who has travelled is referenced
         *     by trip history, and a hard delete would take that with them.
         */
        post: operations["saveOnboardingCompanion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding-connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redeem an agent's invite code, or decline to. Screen 2.1.13.
         * @description Links the traveler to the agent who invited them. Audited on both the
         *     success and the refusal paths — a burst of guesses has to be countable,
         *     which is why a failed attempt is recorded BEFORE the refusal is returned.
         *
         *     Omitting `code` (or sending null) is a first-class exit: "I don't have a
         *     code" writes nothing but the cursor and returns `redeemed: false`.
         *
         *     Every refusal returns 403 with a `detail` naming the reason — expired,
         *     already used, revoked, already connected, claimed by another traveler,
         *     or rate limited. The reason is deliberately specific: a traveler holding
         *     a code that expired needs to know that, not "invalid code".
         */
        post: operations["redeemConnectCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description An amount in minor units plus its currency. */
        Money: {
            /**
             * @description Integer minor units (cents), as a string to preserve precision.
             * @example 1284500
             */
            amount: string;
            /**
             * @description ISO-4217 alphabetic code.
             * @example USD
             */
            currency: string;
        };
        SendTripMessageRequest: {
            /**
             * Format: uuid
             * @description Client-generated UUID v7. The server validates that the embedded timestamp is
             *     recent (Data-Model §21.6) — `assertRecentUuidV7` in `_shared/uuid.ts`. Supplying
             *     the id client-side is what makes a retry idempotent.
             */
            messageId: string;
            /** Format: uuid */
            tripId: string;
            body: string;
            /** @description Documents already registered via POST /trip-document. */
            attachmentDocumentIds?: string[];
        };
        SendTripMessageResponse: {
            /** Format: uuid */
            messageId: string;
            /** Format: uuid */
            conversationId: string;
            /** Format: date-time */
            createdAt: string;
        };
        RequestTripDocumentUploadRequest: {
            /**
             * Format: uuid
             * @description Client-generated UUID v7, validated as recent.
             */
            documentId: string;
            /** Format: uuid */
            tripId: string;
            filename: string;
            /** @description Must be one of the bucket's allowed types. */
            mimeType: string;
            /** @description Integer byte count as a string, for the same precision reason as Money. */
            sizeBytes: string;
            /**
             * @description The document kinds a client may contribute.
             * @enum {string}
             */
            kind: "passport" | "visa" | "insurance_cert" | "photo";
        };
        RequestTripDocumentUploadResponse: {
            /** Format: uuid */
            documentId: string;
            /** @description Signed PUT target, as a path to join to the caller's own Supabase base URL — not an absolute URL. Storage signs against the origin the function sees from inside its container (`http://kong:8000` locally), which resolves nowhere in a browser or on a phone. The caller already holds the right origin, so it does the joining. The storage key itself is still never returned; the path carries the signature, not a readable key. */
            uploadPath: string;
            /** Format: date-time */
            expiresAt: string;
        };
        TripDocumentUrlResponse: {
            /** Format: uuid */
            documentId: string;
            /** @description Signed read target, as a path to join to the caller's own Supabase base URL. See RequestTripDocumentUploadResponse.uploadPath for why this is not absolute. */
            path: string;
            /** Format: date-time */
            expiresAt: string;
            filename: string;
            mimeType: string;
        };
        SaveTestimonialRequest: {
            /**
             * Format: uuid
             * @description Client-generated UUID v7, validated as recent.
             */
            testimonialId: string;
            /**
             * Format: uuid
             * @description Omitted for a reflection not tied to one trip.
             */
            tripId?: string;
            body: string;
            /** @description How the client wants to be credited. */
            attribution?: string;
            /** @description Optional. The prompt is a question, not a star widget. */
            rating?: number;
            /**
             * @description False saves a draft; true moves it to `submitted`. A client can reach no other
             *     state — approval is an agent action.
             * @default false
             */
            submit: boolean;
        };
        SaveTestimonialResponse: {
            /** Format: uuid */
            testimonialId: string;
            /** @enum {string} */
            status: "draft" | "submitted";
            /** Format: date-time */
            submittedAt?: string;
        };
        OnboardingStepRequest: {
            /**
             * @description The step to move the cursor to. Reaching `complete` is not the same as finishing — that is what `complete: true` is for.
             * @enum {string}
             */
            step?: "profile" | "preferences" | "companions" | "connect" | "complete";
            /** @description Marks onboarding finished by setting `onboarding_completed_at`. Mutually exclusive with `step` in practice: this is checked first. */
            complete?: boolean;
        };
        OnboardingStepResponse: {
            ok: boolean;
            /**
             * @description Echoed back when the request moved the cursor.
             * @enum {string}
             */
            step?: "profile" | "preferences" | "companions" | "connect" | "complete";
            /** @description True when the request finished onboarding. */
            completed?: boolean;
        };
        OnboardingOkResponse: {
            ok: boolean;
        };
        OnboardingIdResponse: {
            ok: boolean;
            /** @description The row written. Null when the call wrote nothing — a companions request with `action: none`. */
            id?: string | null;
        };
        /** @description All or nothing. A name with no number looks like a safety net and is not one, so a half-filled contact is a 400 rather than a partial row. Null clears it. Stored as jsonb on `client.emergency_contact`; see Data-Model §6.1. */
        OnboardingEmergencyContact: {
            name?: string;
            /** @description Normalised to E.164, as everywhere else in the schema. */
            phone?: string;
            relationship?: string | null;
        } | null;
        /** @description Six structured fields, not one line — `client.mailing_address_id` is a FK to `address` and there is no free-text address column anywhere. `line1`, `city` and `country` are required TOGETHER or the whole object must be absent or null; two of the three is a 400. */
        OnboardingAddress: {
            line1?: string;
            line2?: string | null;
            city?: string;
            region?: string | null;
            postalCode?: string | null;
            /** @description ISO-3166-1 alpha-2, matching `address.country`'s char(2). */
            country?: string;
        } | null;
        /** @description Expiry and issuing country only. See the endpoint description: sending `number` is a 400, not an ignored field. */
        OnboardingPassport: {
            /**
             * Format: date
             * @description What drives the renewal reminder, and the reason this object exists.
             */
            expiresOn?: string | null;
            issuingCountry?: string | null;
        } | null;
        OnboardingProfileRequest: {
            phone?: string | null;
            /** Format: date */
            dateOfBirth?: string | null;
            emergencyContact?: components["schemas"]["OnboardingEmergencyContact"];
            address?: components["schemas"]["OnboardingAddress"];
            passport?: components["schemas"]["OnboardingPassport"];
            /** @default false */
            advance: boolean;
        };
        /** @description A wholly empty entry is skipped — it is the repeater's last blank line, not a mistake. A number without a program is a 400. */
        OnboardingLoyaltyProgram: {
            program: string;
            /** @description Alphanumeric and hyphens. Anything else is a paste accident, and this is a number somebody will read back to an airline. */
            number?: string | null;
        };
        /** @description Every list is validated against the vocabulary in Data-Model §6.2. Null clears a list; absent leaves it. */
        OnboardingPreferencesRequest: {
            /** @description Free text — the wish list is the traveler's, not a menu. */
            destinations?: string[] | null;
            travelStyles?: ("resort" | "cruise" | "adventure" | "family" | "romantic" | "group")[] | null;
            /** @description `none` is exclusive — with anything else it is a 400. */
            dietary?: ("none" | "vegetarian" | "pescatarian" | "gluten_free" | "halal")[] | null;
            dietaryNotes?: string | null;
            /** @description `none` is exclusive, as with dietary. */
            accessibility?: ("none" | "mobility" | "quiet_room" | "service_animal")[] | null;
            accessibilityNotes?: string | null;
            favoritePastTrips?: string | null;
            /**
             * @description Four bands, not a figure. See the endpoint description for why the prototype's dual-thumb slider did not survive.
             * @enum {string|null}
             */
            budgetBand?: "budget" | "mid" | "premium" | "luxury" | null;
            loyalty?: components["schemas"]["OnboardingLoyaltyProgram"][] | null;
            /** @default false */
            advance: boolean;
        };
        OnboardingCompanionRequest: {
            /**
             * @description `none` writes nothing and exists so "Save & continue" on an already complete list can advance the cursor without inventing a row.
             * @default add
             * @enum {string}
             */
            action: "add" | "edit" | "remove" | "none";
            /**
             * Format: uuid
             * @description Required for `edit` and `remove`.
             */
            id?: string;
            /** @description Required together with lastName for `add` and `edit`. */
            firstName?: string;
            lastName?: string;
            relationship?: string | null;
            /** Format: date */
            dateOfBirth?: string | null;
            /** Format: date */
            passportExpiry?: string | null;
            /** @default false */
            advance: boolean;
        };
        OnboardingConnectRequest: {
            /** @description The agent's invite code. Omitted or null is "I don't have a code" — a first-class exit, not an error. */
            code?: string | null;
            /** @default false */
            advance: boolean;
        };
        OnboardingConnectResponse: {
            ok: boolean;
            /** @description False when the traveler declined to enter a code. */
            redeemed: boolean;
        };
        /** @description RFC 7807 problem details. Every error response uses this shape. */
        Problem: {
            /**
             * Format: uri
             * @default about:blank
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
        };
        HotelSearchRequest: {
            /** @description Free text, as typed. Normalised server-side before it becomes a cache key. */
            destination: string;
            /** Format: date */
            checkIn: string;
            /**
             * Format: date
             * @description Must be after checkIn, and at most 30 nights later.
             */
            checkOut: string;
            /** @default 2 */
            adults: number;
            childrenAges?: number[];
            /** @description Google star classification, 2-5. Not the guest rating. */
            hotelClass?: string[];
            /** @description Google amenity ids. Unknown values are dropped, never forwarded. */
            amenities?: string[];
            minPrice?: number | null;
            maxPrice?: number | null;
            /** @description SerpApi sort id — "3" lowest price, "8" highest rating, "13" most reviewed. Empty means the provider's own relevance. */
            sortBy?: string;
        };
        /**
         * @description ONE indicative nightly rate, deliberately not a list. The provider returns one entry
         *     per booking site, each carrying a source, a logo and a link; a list here — even with
         *     those fields omitted — would invite someone to add the source back "for attribution".
         *     A single scalar cannot.
         */
        HotelRate: {
            /** @description Integer minor units as a string (CLAUDE.md rule 5). */
            amountCents: string;
            currency: string;
            /**
             * @description The only basis published. A total-for-the-stay reads like a quote.
             * @enum {string}
             */
            basis: "night";
            beforeTaxesFees: boolean;
        };
        HotelImage: {
            /** @description Host allow-listed at the mapper and again in web/. */
            url: string;
        };
        HotelLocation: {
            latitude: number;
            longitude: number;
        };
        HotelResult: {
            id: string;
            /** @description Opaque provider id, carried so the later inquiry step can name the hotel. Not a URL. */
            propertyToken?: string | null;
            name: string;
            description?: string | null;
            propertyType?: string | null;
            hotelClass?: number | null;
            overallRating?: number | null;
            reviewCount?: number | null;
            location?: components["schemas"]["HotelLocation"];
            checkInTime?: string | null;
            checkOutTime?: string | null;
            amenities: string[];
            images: components["schemas"]["HotelImage"][];
            ecoCertified: boolean;
            rate?: components["schemas"]["HotelRate"];
        };
        HotelSearchEcho: {
            destination: string;
            /** Format: date */
            checkIn: string;
            /** Format: date */
            checkOut: string;
            adults: number;
            nights: number;
        };
        HotelSearchResponse: {
            /** @description Payload shape version. Part of the cache key, so a change means a cold cache. */
            version: number;
            currency: string;
            totalAvailable?: number | null;
            results: components["schemas"]["HotelResult"][];
            /** @description Always false. Each extra page is another billable search. */
            hasMore: boolean;
            /** @enum {string} */
            source: "live" | "cache" | "stale";
            /** @enum {string|null} */
            degraded?: "budget_exhausted" | "provider_unavailable" | null;
            /** Format: date-time */
            asOf: string;
            /**
             * Format: date-time
             * @description Set only when source is "stale". The page must show how old the prices are.
             */
            staleAsOf?: string | null;
            query: components["schemas"]["HotelSearchEcho"];
        };
    };
    responses: {
        /** @description The request body or query failed validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No such record, or none the caller may see. The two are deliberately indistinguishable. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing or invalid access token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Authenticated, but the caller's role may not perform this action. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    searchHotels: {
        parameters: {
            query?: never;
            header: {
                /** @description Shared secret proving the caller is our own server. */
                "X-STA-Search-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HotelSearchRequest"];
            };
        };
        responses: {
            /** @description Results — live, cached, stale, or degraded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HotelSearchResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    sendTripMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendTripMessageRequest"];
            };
        };
        responses: {
            /** @description The message was posted. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendTripMessageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    requestTripDocumentUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestTripDocumentUploadRequest"];
            };
        };
        responses: {
            /** @description The document row exists and the upload URL is signed. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestTripDocumentUploadResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getTripDocumentUrl: {
        parameters: {
            query: {
                /** @description A `document.id` the caller can already read. */
                documentId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A signed URL, valid for a few minutes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDocumentUrlResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    saveTestimonial: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveTestimonialRequest"];
            };
        };
        responses: {
            /** @description The reflection was saved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveTestimonialResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    setOnboardingStep: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingStepRequest"];
            };
        };
        responses: {
            /** @description The cursor moved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingStepResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    saveOnboardingProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingProfileRequest"];
            };
        };
        responses: {
            /** @description Saved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingOkResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    saveOnboardingPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingPreferencesRequest"];
            };
        };
        responses: {
            /** @description Saved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingIdResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    saveOnboardingCompanion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingCompanionRequest"];
            };
        };
        responses: {
            /** @description Saved. `id` is null when `action` was `none`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingIdResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    redeemConnectCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingConnectRequest"];
            };
        };
        responses: {
            /** @description Redeemed, or declined without error. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingConnectResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /**
             * @description The code was refused, or the caller is not a traveler. `detail`
             *     names which.
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
