-- The cruise fleet: ten lines and 153 ships, curated.
--
-- GENERATED by supabase/scripts/build-cruise-fleet.mts from
-- supabase/scripts/data/cruise_ships.csv. Re-run that, do not hand-edit this.
--
-- WHY THIS EXISTS. cruise_ship cannot be filled by the sync. Free-Travel-APIs §4.8 measured
-- /ships and /ports as unaffordable on a 100-request/month budget — one /filter-options call
-- returned 4,566 ports, and paging the same catalogue at 10 rows a request would cost four
-- and a half months of quota — so both scopes ship disabled, and ships otherwise appear only
-- as stub rows minted when a synced sailing happens to name one. No amount of syncing closes
-- that gap. A curated fleet does.
--
-- WHY IT DOES NOT RACE THE SYNC, which 20260909001124:745 warned it would. That comment
-- predates a reading of the upsert paths, and the paths settle it:
--   * cruise_line upserts on `slug`                     (sync.ts:589, 639)
--   * cruise_ship upserts on `(cruise_line_id, name)`    (sync.ts:703, 758, 1324)
--   * withExistingIds() swaps a freshly minted id for the stored one before writing
--     (sync.ts:1192-1240), so a curated row is MERGED INTO, never duplicated and never 23505.
--   * resolveShipId() looks a ship up by that same natural key BEFORE minting a stub
--     (sync.ts:1294-1330), so a synced sailing attaches to the real hull instead of a stub.
-- The curated rows carry a null provenance pair, which also puts them outside archiveMissing()
-- — it filters `.eq("provider", PROVIDER)`, and "a curated row is nobody's to archive"
-- (sync.ts:1245-1247).
--
-- Ships per line:
--   royal-caribbean   28
--   celebrity         15
--   disney             8
--   princess          16
--   carnival          26
--   virgin-voyages     4
--   norwegian         19
--   holland-america   11
--   msc               22
--   cunard             4
--
-- 151 of 153 carry a photo, every one freely licensed and credited. The rest
-- are NULL rather than wrong — a hull whose only Wikidata match is a renamed predecessor, a
-- ship class, or another line's vessel is refused rather than guessed at. Re-running the
-- generator picks them up as Commons catches up.

-- Nine lines. virgin-voyages is NOT here: 20260909001124:748 already inserted it, for the
-- reason this whole file generalises — track.cruises has no coverage for it, so it can only
-- ever be curated. Its four ships below attach to that existing id.
INSERT INTO public.cruise_line (id, slug, name, display_order, is_booked)
VALUES
    ('01a08376-dc00-7000-8000-000000003001', 'royal-caribbean', 'Royal Caribbean', 10, true),
    ('01a08376-dc00-7000-8000-000000003002', 'celebrity', 'Celebrity', 20, true),
    ('01a08376-dc00-7000-8000-000000003003', 'disney', 'Disney', 30, true),
    ('01a08376-dc00-7000-8000-000000003004', 'princess', 'Princess', 40, true),
    ('01a08376-dc00-7000-8000-000000003005', 'carnival', 'Carnival', 50, true),
    ('01a08376-dc00-7000-8000-000000003006', 'norwegian', 'Norwegian', 70, true),
    ('01a08376-dc00-7000-8000-000000003007', 'holland-america', 'Holland America', 80, true),
    ('01a08376-dc00-7000-8000-000000003008', 'msc', 'MSC Cruises', 900, false),
    ('01a08376-dc00-7000-8000-000000003009', 'cunard', 'Cunard', 910, false)
ON CONFLICT (slug) DO NOTHING;

-- ON CONFLICT (cruise_line_id, name): the ship table's natural key, and the same target the
-- sync uses, so replaying this over a hull the sync already minted is safe rather than a 23503.
--
-- DO UPDATE rather than DO NOTHING, and the WHERE is the whole point. A stub minted by
-- resolveShipId() (sync.ts:1294-1330) is a bare row — name, line, provenance, nothing else —
-- and if one landed before this migration, DO NOTHING would leave that ship permanently
-- without a photo while we are holding one. So the imagery is filled in, and ONLY the imagery:
-- the stub keeps its id, its name, its slug and its provenance, and a row that already has a
-- photo is never overwritten. That is §24.0 rule 3's "curated content as a layer" in the one
-- direction it has to work — curated content filling a gap, never clobbering a decision.
INSERT INTO public.cruise_ship
    (id, cruise_line_id, name, slug, image_url, image_credit, image_license, image_source_url)
VALUES
    ('01a08376-dc00-7000-8000-000000004001', '01a08376-dc00-7000-8000-000000003005', 'Carnival Breeze', 'carnival-breeze',
     'https://upload.wikimedia.org/wikipedia/commons/e/ea/Carnival_Breeze_in_Cozumel_Mexico_(2018)%2C_taken_from_Regal_Princess.jpg', 'Kevin Verbeem from Weyburn, Saskatchewan, Canada / Wikimedia Commons, CC BY-SA 2.0', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:Carnival_Breeze_in_Cozumel_Mexico_(2018),_taken_from_Regal_Princess.jpg'),
    ('01a08376-dc00-7000-8000-000000004002', '01a08376-dc00-7000-8000-000000003005', 'Carnival Celebration', 'carnival-celebration',
     'https://upload.wikimedia.org/wikipedia/commons/7/79/Carnival_Celebration_no_Funchal_(52578168754)_(cropped).jpg', 'A Guy Named Nyal / Wikimedia Commons, CC BY-SA 2.0', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:Carnival_Celebration_no_Funchal_(52578168754)_(cropped).jpg'),
    ('01a08376-dc00-7000-8000-000000004003', '01a08376-dc00-7000-8000-000000003005', 'Carnival Conquest', 'carnival-conquest',
     'https://upload.wikimedia.org/wikipedia/commons/1/1d/Carnival_Conquest_cruiseship.jpg', 'No machine-readable author provided. NormanEinstein assumed (based on copyright claims). / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Carnival_Conquest_cruiseship.jpg'),
    ('01a08376-dc00-7000-8000-000000004004', '01a08376-dc00-7000-8000-000000003005', 'Carnival Dream', 'carnival-dream',
     'https://upload.wikimedia.org/wikipedia/commons/9/9b/Carnival_Dream%2C_docked_at_Nassau_Cruise_Port%2C_Bahamas_(March_14%2C_2024)_01.jpg', 'Kiran891 / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Carnival_Dream,_docked_at_Nassau_Cruise_Port,_Bahamas_(March_14,_2024)_01.jpg'),
    ('01a08376-dc00-7000-8000-000000004005', '01a08376-dc00-7000-8000-000000003005', 'Carnival Elation', 'carnival-elation',
     'https://upload.wikimedia.org/wikipedia/commons/8/89/Elation---Carnival-Lines.jpg', 'P. Alejandro Diaz / Wikimedia Commons, CC BY 2.5', 'CC BY 2.5', 'https://commons.wikimedia.org/wiki/File:Elation---Carnival-Lines.jpg'),
    ('01a08376-dc00-7000-8000-000000004006', '01a08376-dc00-7000-8000-000000003005', 'Carnival Firenze', 'carnival-firenze',
     'https://upload.wikimedia.org/wikipedia/commons/1/13/D7K_3592.jpg', 'Luca Mauri / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:D7K_3592.jpg'),
    ('01a08376-dc00-7000-8000-000000004007', '01a08376-dc00-7000-8000-000000003005', 'Carnival Freedom', 'carnival-freedom',
     'https://upload.wikimedia.org/wikipedia/commons/1/1f/Carnival_Freedom_(ship%2C_2007)_001.jpg', 'Pete Markham / Wikimedia Commons, CC BY-SA 2.0', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:Carnival_Freedom_(ship,_2007)_001.jpg'),
    ('01a08376-dc00-7000-8000-000000004008', '01a08376-dc00-7000-8000-000000003005', 'Carnival Glory', 'carnival-glory',
     'https://upload.wikimedia.org/wikipedia/commons/3/34/Carnival_glory3.jpg', 'Mark Dennis from Canada / Wikimedia Commons, CC BY-SA 2.0', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:Carnival_glory3.jpg'),
    ('01a08376-dc00-7000-8000-000000004009', '01a08376-dc00-7000-8000-000000003005', 'Carnival Horizon', 'carnival-horizon',
     'https://upload.wikimedia.org/wikipedia/commons/f/fe/Carnival_Horizon''s_bow.jpg', 'Mason Piscitelli / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Carnival_Horizon%27s_bow.jpg'),
    ('01a08376-dc00-7000-8000-000000004010', '01a08376-dc00-7000-8000-000000003005', 'Carnival Jubilee', 'carnival-jubilee',
     'https://upload.wikimedia.org/wikipedia/commons/d/da/Carnival_Jubilee_1760.jpg', 'Ein Dahmer / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Carnival_Jubilee_1760.jpg'),
    ('01a08376-dc00-7000-8000-000000004011', '01a08376-dc00-7000-8000-000000003005', 'Carnival Legend', 'carnival-legend',
     'https://upload.wikimedia.org/wikipedia/commons/5/58/Nav%C3%ADo_Carnival_Legend%2C_Skagway%2C_Alaska%2C_Estados_Unidos%2C_2017-08-18%2C_DD_08.jpg', 'Diego Delso / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Nav%C3%ADo_Carnival_Legend,_Skagway,_Alaska,_Estados_Unidos,_2017-08-18,_DD_08.jpg'),
    ('01a08376-dc00-7000-8000-000000004012', '01a08376-dc00-7000-8000-000000003005', 'Carnival Liberty', 'carnival-liberty',
     'https://upload.wikimedia.org/wikipedia/commons/7/7e/Carnival_Liberty_2013.jpg', 'Chargarther / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Carnival_Liberty_2013.jpg'),
    ('01a08376-dc00-7000-8000-000000004013', '01a08376-dc00-7000-8000-000000003005', 'Carnival Luminosa', 'carnival-luminosa',
     'https://upload.wikimedia.org/wikipedia/commons/e/e3/2025-06-04_01_CARNIVAL_LUMINOSA_-_IMO_9398905_%E2%80%93_Ogden_Point_BC_CAN.jpg', 'GRDN711 / Wikimedia Commons, CC BY 4.0', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:2025-06-04_01_CARNIVAL_LUMINOSA_-_IMO_9398905_%E2%80%93_Ogden_Point_BC_CAN.jpg'),
    ('01a08376-dc00-7000-8000-000000004014', '01a08376-dc00-7000-8000-000000003005', 'Carnival Magic', 'carnival-magic',
     'https://upload.wikimedia.org/wikipedia/commons/2/2d/Carnival_Magic_Monaco.jpg', 'Miguelftorres / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Carnival_Magic_Monaco.jpg'),
    ('01a08376-dc00-7000-8000-000000004015', '01a08376-dc00-7000-8000-000000003005', 'Mardi Gras', 'mardi-gras',
     'https://upload.wikimedia.org/wikipedia/commons/3/33/Mardi_Gras_ship_22-12-2020_front_view.jpg', 'kees torn / Wikimedia Commons, CC BY-SA 2.0', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:Mardi_Gras_ship_22-12-2020_front_view.jpg'),
    ('01a08376-dc00-7000-8000-000000004016', '01a08376-dc00-7000-8000-000000003005', 'Carnival Miracle', 'carnival-miracle',
     'https://upload.wikimedia.org/wikipedia/commons/2/26/Carnival_Miracle_July_2011.jpg', 'HurricaneX31 / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Carnival_Miracle_July_2011.jpg'),
    ('01a08376-dc00-7000-8000-000000004017', '01a08376-dc00-7000-8000-000000003005', 'Carnival Panorama', 'carnival-panorama',
     'https://upload.wikimedia.org/wikipedia/commons/6/66/Carnival_Panorama_docked_in_Puerto_Vallarta_1-8-2020_(cropped).jpg', 'Tunestoons / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Carnival_Panorama_docked_in_Puerto_Vallarta_1-8-2020_(cropped).jpg'),
    ('01a08376-dc00-7000-8000-000000004018', '01a08376-dc00-7000-8000-000000003005', 'Carnival Paradise', 'carnival-paradise',
     'https://upload.wikimedia.org/wikipedia/commons/6/60/Ms-paradise-catalina-sm.JPG', 'Beau Hudspeth - Digi-Gen Design Studios - Photography / Wikimedia Commons, CC BY-SA 2.5', 'CC BY-SA 2.5', 'https://commons.wikimedia.org/wiki/File:Ms-paradise-catalina-sm.JPG'),
    ('01a08376-dc00-7000-8000-000000004019', '01a08376-dc00-7000-8000-000000003005', 'Carnival Pride', 'carnival-pride',
     'https://upload.wikimedia.org/wikipedia/commons/b/b9/Carnival_Pride_in_Cabo_San_Lucas.jpg', 'Lisa Andres from Riverside, USA / Wikimedia Commons, CC BY 2.0', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Carnival_Pride_in_Cabo_San_Lucas.jpg'),
    ('01a08376-dc00-7000-8000-000000004020', '01a08376-dc00-7000-8000-000000003005', 'Carnival Radiance', 'carnival-radiance',
     'https://upload.wikimedia.org/wikipedia/commons/7/7b/Carnival_Victory2.jpg', 'Tomás Fano / Wikimedia Commons, CC BY-SA 2.0', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:Carnival_Victory2.jpg'),
    ('01a08376-dc00-7000-8000-000000004021', '01a08376-dc00-7000-8000-000000003005', 'Carnival Spirit', 'carnival-spirit',
     'https://upload.wikimedia.org/wikipedia/commons/8/8c/Carnival_Spirit_at_the_Overseas_Passenger_Terminal_Sydney_July_27%2C_2013_2.jpg', 'Hpeterswald / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Carnival_Spirit_at_the_Overseas_Passenger_Terminal_Sydney_July_27,_2013_2.jpg'),
    ('01a08376-dc00-7000-8000-000000004022', '01a08376-dc00-7000-8000-000000003005', 'Carnival Splendor', 'carnival-splendor',
     'https://upload.wikimedia.org/wikipedia/commons/4/41/US_Navy_101109-N-5684M-067_The_Carnival_cruise_ship_C-V_Splendor_sits_adrift_approximately_150_nautical_miles_southwest_of_San_Diego.jpg', 'U.S. Navy photo by Mass Communication Specialist 3rd Class Dylan McCord / Wikimedia Commons, Public domain', 'Public domain', 'https://commons.wikimedia.org/wiki/File:US_Navy_101109-N-5684M-067_The_Carnival_cruise_ship_C-V_Splendor_sits_adrift_approximately_150_nautical_miles_southwest_of_San_Diego.jpg'),
    ('01a08376-dc00-7000-8000-000000004023', '01a08376-dc00-7000-8000-000000003005', 'Carnival Sunrise', 'carnival-sunrise',
     'https://upload.wikimedia.org/wikipedia/commons/8/87/Carnival_Sunrise_Anchored_in_Grand_Cayman_(May_2025).jpg', 'Jack Adamenko / Wikimedia Commons, CC BY 4.0', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:Carnival_Sunrise_Anchored_in_Grand_Cayman_(May_2025).jpg'),
    ('01a08376-dc00-7000-8000-000000004024', '01a08376-dc00-7000-8000-000000003005', 'Carnival Sunshine', 'carnival-sunshine',
     'https://upload.wikimedia.org/wikipedia/commons/f/fb/CarnivalSunshineCL.JPG', 'Corentin Lewis / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:CarnivalSunshineCL.JPG'),
    ('01a08376-dc00-7000-8000-000000004025', '01a08376-dc00-7000-8000-000000003005', 'Carnival Valor', 'carnival-valor',
     'https://upload.wikimedia.org/wikipedia/commons/6/63/Carnival_Valor3.jpg', 'Marcin Wichary from San Francisco, U.S.A. / Wikimedia Commons, CC BY 2.0', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Carnival_Valor3.jpg'),
    ('01a08376-dc00-7000-8000-000000004026', '01a08376-dc00-7000-8000-000000003005', 'Carnival Venezia', 'carnival-venezia',
     'https://upload.wikimedia.org/wikipedia/commons/2/2b/Carnival_Venezia''s_maiden_arrival_at_Bermuda_2.jpg', 'Yankeesman312 / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Carnival_Venezia%27s_maiden_arrival_at_Bermuda_2.jpg'),
    ('01a08376-dc00-7000-8000-000000004027', '01a08376-dc00-7000-8000-000000003001', 'Adventure of the Seas', 'adventure-of-the-seas',
     'https://upload.wikimedia.org/wikipedia/commons/c/cf/Adventure_of_the_Seas_Lat.jpg', 'Davidbenjaminlat / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Adventure_of_the_Seas_Lat.jpg'),
    ('01a08376-dc00-7000-8000-000000004028', '01a08376-dc00-7000-8000-000000003001', 'Allure of the Seas', 'allure-of-the-seas',
     'https://upload.wikimedia.org/wikipedia/commons/2/24/Allure_of_the_Seas_(ship%2C_2009)_001.jpg', 'Jorge in Brazil / Wikimedia Commons, CC BY 2.0', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Allure_of_the_Seas_(ship,_2009)_001.jpg'),
    ('01a08376-dc00-7000-8000-000000004029', '01a08376-dc00-7000-8000-000000003001', 'Anthem of the Seas', 'anthem-of-the-seas',
     'https://upload.wikimedia.org/wikipedia/commons/f/fb/Anthem_of_the_Seas%2C_docked_at_Nassau_Cruise_Port%2C_Bahamas_(March_14%2C_2024)_16-9.jpg', 'Kiran891 / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Anthem_of_the_Seas,_docked_at_Nassau_Cruise_Port,_Bahamas_(March_14,_2024)_16-9.jpg'),
    ('01a08376-dc00-7000-8000-000000004030', '01a08376-dc00-7000-8000-000000003001', 'Brilliance of the Seas', 'brilliance-of-the-seas',
     'https://upload.wikimedia.org/wikipedia/commons/b/b7/BOS_at_Valetta_121410.JPG', 'Detroitmark / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:BOS_at_Valetta_121410.JPG'),
    ('01a08376-dc00-7000-8000-000000004031', '01a08376-dc00-7000-8000-000000003001', 'Enchantment of the Seas', 'enchantment-of-the-seas',
     'https://upload.wikimedia.org/wikipedia/commons/8/8a/Enchantment_of_the_Seas.jpg', 'Original uploader was Rageousgtx at en.wikipedia / Wikimedia Commons, Public domain', 'Public domain', 'https://commons.wikimedia.org/wiki/File:Enchantment_of_the_Seas.jpg'),
    ('01a08376-dc00-7000-8000-000000004032', '01a08376-dc00-7000-8000-000000003001', 'Explorer of the Seas', 'explorer-of-the-seas',
     'https://upload.wikimedia.org/wikipedia/commons/9/95/Explorer_of_the_Seas%2C_Fremantle%2C_2015_(03).JPG', 'Bahnfrend / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Explorer_of_the_Seas,_Fremantle,_2015_(03).JPG'),
    ('01a08376-dc00-7000-8000-000000004033', '01a08376-dc00-7000-8000-000000003001', 'Freedom of the Seas', 'freedom-of-the-seas',
     'https://upload.wikimedia.org/wikipedia/commons/3/36/Freedom_of_the_Seas_at_Port_Miami_(March_15%2C_2024).jpg', 'Kiran891 / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Freedom_of_the_Seas_at_Port_Miami_(March_15,_2024).jpg'),
    ('01a08376-dc00-7000-8000-000000004034', '01a08376-dc00-7000-8000-000000003001', 'Grandeur of the Seas', 'grandeur-of-the-seas',
     'https://upload.wikimedia.org/wikipedia/commons/6/68/GrandeuroftheSeas-NOLA.jpg', 'J. Glover / Wikimedia Commons, CC BY-SA 2.0', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:GrandeuroftheSeas-NOLA.jpg'),
    ('01a08376-dc00-7000-8000-000000004035', '01a08376-dc00-7000-8000-000000003001', 'Harmony of the Seas', 'harmony-of-the-seas',
     'https://upload.wikimedia.org/wikipedia/commons/1/1b/Harmony_of_the_Seas_-_Rotterdam.jpg', 'Michiel1972 / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Harmony_of_the_Seas_-_Rotterdam.jpg'),
    ('01a08376-dc00-7000-8000-000000004036', '01a08376-dc00-7000-8000-000000003001', 'Icon of the Seas', 'icon-of-the-seas',
     'https://upload.wikimedia.org/wikipedia/commons/6/66/Icon_of_the_Seas_Puerto_Rico_2025_(cropped).jpg', 'Corey Seeman / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Icon_of_the_Seas_Puerto_Rico_2025_(cropped).jpg'),
    ('01a08376-dc00-7000-8000-000000004037', '01a08376-dc00-7000-8000-000000003001', 'Independence of the Seas', 'independence-of-the-seas',
     'https://upload.wikimedia.org/wikipedia/commons/3/3b/Independence_of_the_Seas_at_Port_Miami_(March_15%2C_2024).jpg', 'Kiran891 / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Independence_of_the_Seas_at_Port_Miami_(March_15,_2024).jpg'),
    ('01a08376-dc00-7000-8000-000000004038', '01a08376-dc00-7000-8000-000000003001', 'Jewel of the Seas', 'jewel-of-the-seas',
     'https://upload.wikimedia.org/wikipedia/commons/3/3d/Jewel_of_the_Seas_G628.jpg', 'User:Dave souza / Wikimedia Commons, CC BY-SA 2.5', 'CC BY-SA 2.5', 'https://commons.wikimedia.org/wiki/File:Jewel_of_the_Seas_G628.jpg'),
    ('01a08376-dc00-7000-8000-000000004039', '01a08376-dc00-7000-8000-000000003001', 'Liberty of the Seas', 'liberty-of-the-seas',
     'https://upload.wikimedia.org/wikipedia/commons/3/35/Liberty_Of_The_Seas_22-04-2007.JPG', 'Hassocks5489 at English Wikipedia / Wikimedia Commons, Public domain', 'Public domain', 'https://commons.wikimedia.org/wiki/File:Liberty_Of_The_Seas_22-04-2007.JPG'),
    ('01a08376-dc00-7000-8000-000000004040', '01a08376-dc00-7000-8000-000000003001', 'Mariner of the Seas', 'mariner-of-the-seas',
     'https://upload.wikimedia.org/wikipedia/commons/3/3c/Mariner_of_the_Seas_in_San_Juan_at_Dusk.jpg', 'ATren / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Mariner_of_the_Seas_in_San_Juan_at_Dusk.jpg'),
    ('01a08376-dc00-7000-8000-000000004041', '01a08376-dc00-7000-8000-000000003001', 'Navigator of the Seas', 'navigator-of-the-seas',
     'https://upload.wikimedia.org/wikipedia/commons/1/10/Navigator_of_the_Seas_(ship%2C_2002)_in_Ensenada%2C_Mexico_(August_2024)_2.jpg', 'Jack Adamenko / Wikimedia Commons, CC BY 4.0', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:Navigator_of_the_Seas_(ship,_2002)_in_Ensenada,_Mexico_(August_2024)_2.jpg'),
    ('01a08376-dc00-7000-8000-000000004042', '01a08376-dc00-7000-8000-000000003001', 'Oasis of the Seas', 'oasis-of-the-seas',
     'https://upload.wikimedia.org/wikipedia/commons/8/89/Oasis_of_the_Seas.jpg', 'Baldwin040 / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Oasis_of_the_Seas.jpg'),
    ('01a08376-dc00-7000-8000-000000004043', '01a08376-dc00-7000-8000-000000003001', 'Odyssey of the Seas', 'odyssey-of-the-seas',
     'https://upload.wikimedia.org/wikipedia/commons/8/8e/Odyssey_of_the_Seas_moored_in_Akandia_Harbour_in_Port_of_Rhodes_8_September_2024_(cropped).jpg', 'Pjotr Mahhonin / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Odyssey_of_the_Seas_moored_in_Akandia_Harbour_in_Port_of_Rhodes_8_September_2024_(cropped).jpg'),
    ('01a08376-dc00-7000-8000-000000004044', '01a08376-dc00-7000-8000-000000003001', 'Ovation of the Seas', 'ovation-of-the-seas',
     'https://upload.wikimedia.org/wikipedia/commons/4/49/Ovation_of_the_Seas_(26417060696)_(cropped).jpg', 'kees torn / Wikimedia Commons, CC BY-SA 2.0', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:Ovation_of_the_Seas_(26417060696)_(cropped).jpg'),
    ('01a08376-dc00-7000-8000-000000004045', '01a08376-dc00-7000-8000-000000003001', 'Quantum of the Seas', 'quantum-of-the-seas',
     'https://upload.wikimedia.org/wikipedia/commons/8/88/Quantum_of_the_Seas_-_Wedel_04.jpg', 'Frank Schwichtenberg / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Quantum_of_the_Seas_-_Wedel_04.jpg'),
    ('01a08376-dc00-7000-8000-000000004046', '01a08376-dc00-7000-8000-000000003001', 'Radiance of the Seas', 'radiance-of-the-seas',
     'https://upload.wikimedia.org/wikipedia/commons/1/15/Radiance_of_the_Seas_-_Juneau%2C_AK.jpg', 'Fletcher6 / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Radiance_of_the_Seas_-_Juneau,_AK.jpg'),
    ('01a08376-dc00-7000-8000-000000004047', '01a08376-dc00-7000-8000-000000003001', 'Rhapsody of the Seas', 'rhapsody-of-the-seas',
     'https://upload.wikimedia.org/wikipedia/commons/2/2c/%22Rhapsody_of_the_Seas%22_in_Queen_Charlotte_Sound_(6256235927).jpg', 'Sid Mosdell from New Zealand / Wikimedia Commons, CC BY 2.0', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:%22Rhapsody_of_the_Seas%22_in_Queen_Charlotte_Sound_(6256235927).jpg'),
    ('01a08376-dc00-7000-8000-000000004048', '01a08376-dc00-7000-8000-000000003001', 'Serenade of the Seas', 'serenade-of-the-seas',
     'https://upload.wikimedia.org/wikipedia/commons/8/82/RCI_Serenade_of_the_Seas.JPG', 'This image or media was taken or created by Matt H. Wade . To see his entire portfolio, click here . @ thatmattwade This image is protected by copyright ! If you would like to use  / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:RCI_Serenade_of_the_Seas.JPG'),
    ('01a08376-dc00-7000-8000-000000004049', '01a08376-dc00-7000-8000-000000003001', 'Spectrum of the Seas', 'spectrum-of-the-seas',
     'https://upload.wikimedia.org/wikipedia/commons/7/7e/Spectrum_of_the_Seas_01.jpg', 'Dickelbers / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Spectrum_of_the_Seas_01.jpg'),
    ('01a08376-dc00-7000-8000-000000004050', '01a08376-dc00-7000-8000-000000003001', 'Symphony of the Seas', 'symphony-of-the-seas',
     'https://upload.wikimedia.org/wikipedia/commons/d/dd/SymphonyOfTheSeas_(cropped)_02.jpg', 'Darthvadrouw / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:SymphonyOfTheSeas_(cropped)_02.jpg'),
    ('01a08376-dc00-7000-8000-000000004051', '01a08376-dc00-7000-8000-000000003001', 'Utopia of the Seas', 'utopia-of-the-seas',
     'https://upload.wikimedia.org/wikipedia/commons/1/1d/Utopia_of_the_Seas_La_Rochelle-b_(cropped).jpg', 'Didier Duforest / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Utopia_of_the_Seas_La_Rochelle-b_(cropped).jpg'),
    ('01a08376-dc00-7000-8000-000000004052', '01a08376-dc00-7000-8000-000000003001', 'Vision of the Seas', 'vision-of-the-seas',
     'https://upload.wikimedia.org/wikipedia/commons/5/50/Vision_of_the_seas_nassau.jpg', 'Joost J. Bakker from IJmuiden / Wikimedia Commons, CC BY 2.0', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Vision_of_the_seas_nassau.jpg'),
    ('01a08376-dc00-7000-8000-000000004053', '01a08376-dc00-7000-8000-000000003001', 'Voyager of the Seas', 'voyager-of-the-seas',
     'https://upload.wikimedia.org/wikipedia/commons/5/50/Voyager_of_the_Seas_Costa_Maya_2023.jpg', 'Larry D. Moore / Wikimedia Commons, CC BY 4.0', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:Voyager_of_the_Seas_Costa_Maya_2023.jpg'),
    ('01a08376-dc00-7000-8000-000000004054', '01a08376-dc00-7000-8000-000000003001', 'Wonder of the Seas', 'wonder-of-the-seas',
     'https://upload.wikimedia.org/wikipedia/commons/0/09/Wonder_of_the_Seas_Jan_30_2025.jpg', 'Master0Garfield / Wikimedia Commons, CC0', 'CC0', 'https://commons.wikimedia.org/wiki/File:Wonder_of_the_Seas_Jan_30_2025.jpg'),
    ('01a08376-dc00-7000-8000-000000004055', '01a08376-dc00-7000-8000-000000003006', 'Norwegian Aqua', 'norwegian-aqua',
     'https://upload.wikimedia.org/wikipedia/commons/3/36/Norwegian_Aqua_southampton.JPG', 'Geni / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Norwegian_Aqua_southampton.JPG'),
    ('01a08376-dc00-7000-8000-000000004056', '01a08376-dc00-7000-8000-000000003006', 'Norwegian Bliss', 'norwegian-bliss',
     'https://upload.wikimedia.org/wikipedia/commons/7/77/World_Dream_Panorama.jpg', 'Arno Redenius / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:World_Dream_Panorama.jpg'),
    ('01a08376-dc00-7000-8000-000000004057', '01a08376-dc00-7000-8000-000000003006', 'Norwegian Breakaway', 'norwegian-breakaway',
     'https://upload.wikimedia.org/wikipedia/commons/6/67/Norwegian_Breakaway_10.JPG', 'Dickelbers / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Norwegian_Breakaway_10.JPG'),
    ('01a08376-dc00-7000-8000-000000004058', '01a08376-dc00-7000-8000-000000003006', 'Norwegian Dawn', 'norwegian-dawn',
     'https://upload.wikimedia.org/wikipedia/commons/0/09/Norwegian_Dawn_at_Lower_Manhattan.jpg', 'The original uploader was Uris at English Wikipedia . / Wikimedia Commons, BSD', 'BSD', 'https://commons.wikimedia.org/wiki/File:Norwegian_Dawn_at_Lower_Manhattan.jpg'),
    ('01a08376-dc00-7000-8000-000000004059', '01a08376-dc00-7000-8000-000000003006', 'Norwegian Encore', 'norwegian-encore',
     'https://upload.wikimedia.org/wikipedia/commons/c/cf/2026-05-02_02_NORWEGIAN_ENCORE_-_IMO_9751511_-_Ogden_Point%2C_BC_CAN.jpg', 'Gordon Leggett / Wikimedia Commons, CC BY 4.0', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:2026-05-02_02_NORWEGIAN_ENCORE_-_IMO_9751511_-_Ogden_Point,_BC_CAN.jpg'),
    ('01a08376-dc00-7000-8000-000000004060', '01a08376-dc00-7000-8000-000000003006', 'Norwegian Epic', 'norwegian-epic',
     'https://upload.wikimedia.org/wikipedia/commons/d/d6/Norwegian_Epic_1_(cropped)_(cropped).JPG', 'This image photographed by Brian Burnell with permission was uploaded to Commons by George Hutchinson . To see his entire portfolio, click here . Permission to upload photographs b / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Norwegian_Epic_1_(cropped)_(cropped).JPG'),
    ('01a08376-dc00-7000-8000-000000004061', '01a08376-dc00-7000-8000-000000003006', 'Norwegian Escape', 'norwegian-escape',
     'https://upload.wikimedia.org/wikipedia/commons/b/b1/2023-03-04_01_NORWEGIAN_ESCAPE_-_IMO_9677076_-_Port_Canaveral_FL_USA.jpg', 'Gordon Leggett / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:2023-03-04_01_NORWEGIAN_ESCAPE_-_IMO_9677076_-_Port_Canaveral_FL_USA.jpg'),
    ('01a08376-dc00-7000-8000-000000004062', '01a08376-dc00-7000-8000-000000003006', 'Norwegian Gem', 'norwegian-gem',
     'https://upload.wikimedia.org/wikipedia/commons/d/d3/Norwegian_gem_in_Sicily_2008.jpg', 'Corgi5623 ( talk ) / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Norwegian_gem_in_Sicily_2008.jpg'),
    ('01a08376-dc00-7000-8000-000000004063', '01a08376-dc00-7000-8000-000000003006', 'Norwegian Getaway', 'norwegian-getaway',
     'https://upload.wikimedia.org/wikipedia/commons/c/ca/Norwegian_Getaway_18.JPG', 'Dickelbers / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Norwegian_Getaway_18.JPG'),
    ('01a08376-dc00-7000-8000-000000004064', '01a08376-dc00-7000-8000-000000003006', 'Norwegian Jade', 'norwegian-jade',
     'https://upload.wikimedia.org/wikipedia/commons/6/6b/Norwegian_Jade_(ship%2C_2006)_IMO_9304057%3B_in_Split%2C_2011-10-10%3B_(1).jpg', 'Ivan T. / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Norwegian_Jade_(ship,_2006)_IMO_9304057;_in_Split,_2011-10-10;_(1).jpg'),
    ('01a08376-dc00-7000-8000-000000004065', '01a08376-dc00-7000-8000-000000003006', 'Norwegian Jewel', 'norwegian-jewel',
     'https://upload.wikimedia.org/wikipedia/commons/9/9a/Norwegian_Jewel_Newport_September_2010.jpg', 'A.jo / Wikimedia Commons, Public domain', 'Public domain', 'https://commons.wikimedia.org/wiki/File:Norwegian_Jewel_Newport_September_2010.jpg'),
    ('01a08376-dc00-7000-8000-000000004066', '01a08376-dc00-7000-8000-000000003006', 'Norwegian Joy', 'norwegian-joy',
     'https://upload.wikimedia.org/wikipedia/commons/1/10/Norwegian_Joy.jpg', 'Arno Redenius / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Norwegian_Joy.jpg'),
    ('01a08376-dc00-7000-8000-000000004067', '01a08376-dc00-7000-8000-000000003006', 'Norwegian Pearl', 'norwegian-pearl',
     'https://upload.wikimedia.org/wikipedia/commons/9/9b/Norwegian_Pearl_in_Papenburg%2C_Germany.jpg', 'The original uploader was OneCyclone at English Wikipedia . / Wikimedia Commons, CC BY-SA 2.0', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:Norwegian_Pearl_in_Papenburg,_Germany.jpg'),
    ('01a08376-dc00-7000-8000-000000004068', '01a08376-dc00-7000-8000-000000003006', 'Norwegian Prima', 'norwegian-prima',
     'https://upload.wikimedia.org/wikipedia/commons/d/d4/Norwegian_Prima_in_Amsterdam_(cropped).jpg', 'Chrissy85 / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Norwegian_Prima_in_Amsterdam_(cropped).jpg'),
    ('01a08376-dc00-7000-8000-000000004069', '01a08376-dc00-7000-8000-000000003006', 'Norwegian Sky', 'norwegian-sky',
     'https://upload.wikimedia.org/wikipedia/commons/5/58/2023-09-04_01_NORWEGIAN_SKY_-_IMO_9128532_-_Charlottetown_PEI_CAN.jpg', 'Gordon Leggett / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:2023-09-04_01_NORWEGIAN_SKY_-_IMO_9128532_-_Charlottetown_PEI_CAN.jpg'),
    ('01a08376-dc00-7000-8000-000000004070', '01a08376-dc00-7000-8000-000000003006', 'Norwegian Spirit', 'norwegian-spirit',
     'https://upload.wikimedia.org/wikipedia/commons/6/63/Norwegian_Spirit.jpg', 'maxum255 / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Norwegian_Spirit.jpg'),
    ('01a08376-dc00-7000-8000-000000004071', '01a08376-dc00-7000-8000-000000003006', 'Norwegian Star', 'norwegian-star',
     'https://upload.wikimedia.org/wikipedia/commons/5/5c/Norwegian_Star_leaving_Tallinn_19_May_2013.JPG', 'Pjotr Mahhonin / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Norwegian_Star_leaving_Tallinn_19_May_2013.JPG'),
    ('01a08376-dc00-7000-8000-000000004072', '01a08376-dc00-7000-8000-000000003006', 'Norwegian Sun', 'norwegian-sun',
     'https://upload.wikimedia.org/wikipedia/commons/a/a6/NCLSunAlaska.jpg', 'Bev and Richard Martin. / Wikimedia Commons, CC BY 2.0', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:NCLSunAlaska.jpg'),
    ('01a08376-dc00-7000-8000-000000004073', '01a08376-dc00-7000-8000-000000003006', 'Norwegian Viva', 'norwegian-viva',
     'https://upload.wikimedia.org/wikipedia/commons/a/ad/Norwegian_Viva_Mar_1_2024.jpg', 'Master0Garfield / Wikimedia Commons, CC0', 'CC0', 'https://commons.wikimedia.org/wiki/File:Norwegian_Viva_Mar_1_2024.jpg'),
    ('01a08376-dc00-7000-8000-000000004074', '01a08376-dc00-7000-8000-000000003008', 'MSC Armonia', 'msc-armonia',
     'https://upload.wikimedia.org/wikipedia/commons/a/a6/MSC_Armonia_(ship%2C_2001)_IMO_9210141%3B_in_Split%2C_2011-10-25_(2).jpg', 'Ivan T. / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:MSC_Armonia_(ship,_2001)_IMO_9210141;_in_Split,_2011-10-25_(2).jpg'),
    ('01a08376-dc00-7000-8000-000000004075', '01a08376-dc00-7000-8000-000000003008', 'MSC Bellissima', 'msc-bellissima',
     'https://upload.wikimedia.org/wikipedia/commons/6/68/MSC_Bellissima_20190226_190550.jpg', 'Hashar / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:MSC_Bellissima_20190226_190550.jpg'),
    ('01a08376-dc00-7000-8000-000000004076', '01a08376-dc00-7000-8000-000000003008', 'MSC Divina', 'msc-divina',
     'https://upload.wikimedia.org/wikipedia/commons/0/04/MSC_Divina_a_Istanbul.JPG', 'Mllturro / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:MSC_Divina_a_Istanbul.JPG'),
    ('01a08376-dc00-7000-8000-000000004077', '01a08376-dc00-7000-8000-000000003008', 'MSC Euribia', 'msc-euribia',
     'https://upload.wikimedia.org/wikipedia/commons/0/0b/MSC_Euribia_leaving_Kiel_26.jpg', 'HenSti / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:MSC_Euribia_leaving_Kiel_26.jpg'),
    ('01a08376-dc00-7000-8000-000000004078', '01a08376-dc00-7000-8000-000000003008', 'MSC Fantasia', 'msc-fantasia',
     'https://upload.wikimedia.org/wikipedia/commons/8/80/MSC_Fantasia_2012_2.jpg', 'Benjamin Nagel / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:MSC_Fantasia_2012_2.jpg'),
    ('01a08376-dc00-7000-8000-000000004079', '01a08376-dc00-7000-8000-000000003008', 'MSC Grandiosa', 'msc-grandiosa',
     'https://upload.wikimedia.org/wikipedia/commons/d/d6/Vertrek_MSC_GRANDIOSA_(49018550362).jpg', 'kees torn / Wikimedia Commons, CC BY-SA 2.0', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:Vertrek_MSC_GRANDIOSA_(49018550362).jpg'),
    ('01a08376-dc00-7000-8000-000000004080', '01a08376-dc00-7000-8000-000000003008', 'MSC Lirica', 'msc-lirica',
     'https://upload.wikimedia.org/wikipedia/commons/9/9c/MSC_Lirica_Kiel.jpg', 'VollwertBIT / Wikimedia Commons, CC BY-SA 2.5', 'CC BY-SA 2.5', 'https://commons.wikimedia.org/wiki/File:MSC_Lirica_Kiel.jpg'),
    ('01a08376-dc00-7000-8000-000000004081', '01a08376-dc00-7000-8000-000000003008', 'MSC Magnifica', 'msc-magnifica',
     'https://upload.wikimedia.org/wikipedia/commons/6/63/MSC_Magnifica_at_Ocean_Cay_MSC_Marine_Reserve_(March_12%2C_2024)_01.jpg', 'Kiran891 / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:MSC_Magnifica_at_Ocean_Cay_MSC_Marine_Reserve_(March_12,_2024)_01.jpg'),
    ('01a08376-dc00-7000-8000-000000004082', '01a08376-dc00-7000-8000-000000003008', 'MSC Meraviglia', 'msc-meraviglia',
     'https://upload.wikimedia.org/wikipedia/commons/8/87/MSC_Meraviglia_Grand_Harbour_Malta_20180307_03_(cropped).jpg', 'Estormiz / Wikimedia Commons, CC0', 'CC0', 'https://commons.wikimedia.org/wiki/File:MSC_Meraviglia_Grand_Harbour_Malta_20180307_03_(cropped).jpg'),
    ('01a08376-dc00-7000-8000-000000004083', '01a08376-dc00-7000-8000-000000003008', 'MSC Musica', 'msc-musica',
     'https://upload.wikimedia.org/wikipedia/commons/8/89/Oasis_of_the_Seas.jpg', 'Baldwin040 / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Oasis_of_the_Seas.jpg'),
    ('01a08376-dc00-7000-8000-000000004084', '01a08376-dc00-7000-8000-000000003008', 'MSC Opera', 'msc-opera',
     'https://upload.wikimedia.org/wikipedia/commons/7/78/MSC_Opera.jpg', 'VollwertBIT / Wikimedia Commons, CC BY-SA 2.5', 'CC BY-SA 2.5', 'https://commons.wikimedia.org/wiki/File:MSC_Opera.jpg'),
    ('01a08376-dc00-7000-8000-000000004085', '01a08376-dc00-7000-8000-000000003008', 'MSC Orchestra', 'msc-orchestra',
     'https://upload.wikimedia.org/wikipedia/commons/6/6b/Mscorchestra.jpg', 'Ömür Tanyel / Wikimedia Commons, Public domain', 'Public domain', 'https://commons.wikimedia.org/wiki/File:Mscorchestra.jpg'),
    ('01a08376-dc00-7000-8000-000000004086', '01a08376-dc00-7000-8000-000000003008', 'MSC Poesia', 'msc-poesia',
     'https://upload.wikimedia.org/wikipedia/commons/c/ce/MSC_POESIA_Jam_Cruise_8_Grand_Cayman_at_anchor.jpg', 'Pedant / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:MSC_POESIA_Jam_Cruise_8_Grand_Cayman_at_anchor.jpg'),
    ('01a08376-dc00-7000-8000-000000004087', '01a08376-dc00-7000-8000-000000003008', 'MSC Preziosa', 'msc-preziosa',
     'https://upload.wikimedia.org/wikipedia/commons/1/12/MSC_PREZIOSA_(40907190273).jpg', 'kees torn / Wikimedia Commons, CC BY-SA 2.0', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:MSC_PREZIOSA_(40907190273).jpg'),
    ('01a08376-dc00-7000-8000-000000004088', '01a08376-dc00-7000-8000-000000003008', 'MSC Seascape', 'msc-seascape',
     'https://upload.wikimedia.org/wikipedia/commons/2/23/MSC_Seascape_cruise_ship_3_(cropped).jpg', 'Rene Cortin / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:MSC_Seascape_cruise_ship_3_(cropped).jpg'),
    ('01a08376-dc00-7000-8000-000000004089', '01a08376-dc00-7000-8000-000000003008', 'MSC Seashore', 'msc-seashore',
     'https://upload.wikimedia.org/wikipedia/commons/2/20/MSC_Seashore.png', 'Cenk Akkaya / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:MSC_Seashore.png'),
    ('01a08376-dc00-7000-8000-000000004090', '01a08376-dc00-7000-8000-000000003008', 'MSC Seaside', 'msc-seaside',
     'https://upload.wikimedia.org/wikipedia/commons/9/9b/MSC_Seaside_01.jpg', 'Dickelbers / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:MSC_Seaside_01.jpg'),
    ('01a08376-dc00-7000-8000-000000004091', '01a08376-dc00-7000-8000-000000003008', 'MSC Sinfonia', 'msc-sinfonia',
     'https://upload.wikimedia.org/wikipedia/commons/8/83/MSC_Sinfonia_2.JPG', 'Gerd Fahrenhorst / Wikimedia Commons, Public domain', 'Public domain', 'https://commons.wikimedia.org/wiki/File:MSC_Sinfonia_2.JPG'),
    ('01a08376-dc00-7000-8000-000000004092', '01a08376-dc00-7000-8000-000000003008', 'MSC Splendida', 'msc-splendida',
     'https://upload.wikimedia.org/wikipedia/commons/a/a8/MSC_Splendida.jpg', 'Jolly Janner / Wikimedia Commons, Public domain', 'Public domain', 'https://commons.wikimedia.org/wiki/File:MSC_Splendida.jpg'),
    ('01a08376-dc00-7000-8000-000000004093', '01a08376-dc00-7000-8000-000000003008', 'MSC Virtuosa', 'msc-virtuosa',
     'https://upload.wikimedia.org/wikipedia/commons/1/15/MSC_Virtuosa_at_Liverpool_202106-7.jpg', 'Rodhullandemu / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:MSC_Virtuosa_at_Liverpool_202106-7.jpg'),
    ('01a08376-dc00-7000-8000-000000004094', '01a08376-dc00-7000-8000-000000003008', 'MSC World America', 'msc-world-america',
     NULL, NULL, NULL, NULL),
    ('01a08376-dc00-7000-8000-000000004095', '01a08376-dc00-7000-8000-000000003008', 'MSC World Europa', 'msc-world-europa',
     'https://upload.wikimedia.org/wikipedia/commons/b/bd/MSC_World_Europa_La_Rochelle.jpg', 'Didier Duforest / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:MSC_World_Europa_La_Rochelle.jpg'),
    ('01a08376-dc00-7000-8000-000000004096', '01a08376-dc00-7000-8000-000000003004', 'Caribbean Princess', 'caribbean-princess',
     'https://upload.wikimedia.org/wikipedia/commons/1/18/Caribbean_Princess_at_St._Thomas%2C_USVI.jpg', 'Yankeesman312 / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Caribbean_Princess_at_St._Thomas,_USVI.jpg'),
    ('01a08376-dc00-7000-8000-000000004097', '01a08376-dc00-7000-8000-000000003004', 'Coral Princess', 'coral-princess',
     'https://upload.wikimedia.org/wikipedia/commons/e/ed/Coral_Princess_-_IMO_9229659_(2937202430).jpg', 'Cliff from Arlington, Virginia, USA / Wikimedia Commons, CC BY 2.0', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Coral_Princess_-_IMO_9229659_(2937202430).jpg'),
    ('01a08376-dc00-7000-8000-000000004098', '01a08376-dc00-7000-8000-000000003004', 'Crown Princess', 'crown-princess',
     'https://upload.wikimedia.org/wikipedia/commons/8/89/Crown_Princess.jpg', 'CB2379 at English Wikipedia / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Crown_Princess.jpg'),
    ('01a08376-dc00-7000-8000-000000004099', '01a08376-dc00-7000-8000-000000003004', 'Discovery Princess', 'discovery-princess',
     'https://upload.wikimedia.org/wikipedia/commons/7/7a/Discovery_Princess.jpg', 'Russell Keller / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Discovery_Princess.jpg'),
    ('01a08376-dc00-7000-8000-000000004100', '01a08376-dc00-7000-8000-000000003004', 'Emerald Princess', 'emerald-princess',
     'https://upload.wikimedia.org/wikipedia/commons/0/08/Emerald_Princess_Stockholm_2011a.jpg', 'Holger.Ellgaard / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Emerald_Princess_Stockholm_2011a.jpg'),
    ('01a08376-dc00-7000-8000-000000004101', '01a08376-dc00-7000-8000-000000003004', 'Enchanted Princess', 'enchanted-princess',
     'https://upload.wikimedia.org/wikipedia/commons/7/7d/Princess_Cruise_Lines_Enchanted_Princess_(cropped).jpg', 'A Guy Named Nyal ( photos · photo sets ) / Wikimedia Commons, CC BY-SA 2.0', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:Princess_Cruise_Lines_Enchanted_Princess_(cropped).jpg'),
    ('01a08376-dc00-7000-8000-000000004102', '01a08376-dc00-7000-8000-000000003004', 'Grand Princess', 'grand-princess',
     'https://upload.wikimedia.org/wikipedia/commons/9/9f/Grand_Princess_and_Football_on_TV.JPG', 'This image photographed by Brian Burnell with permission was uploaded to Commons by George Hutchinson . To see his entire portfolio, click here . Permission to upload photographs b / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Grand_Princess_and_Football_on_TV.JPG'),
    ('01a08376-dc00-7000-8000-000000004103', '01a08376-dc00-7000-8000-000000003004', 'Island Princess', 'island-princess',
     'https://upload.wikimedia.org/wikipedia/commons/e/ed/Island_Princess_in_Port_Everglades.JPG', 'Jean-Philippe Boulet / Wikimedia Commons, CC BY 3.0', 'CC BY 3.0', 'https://commons.wikimedia.org/wiki/File:Island_Princess_in_Port_Everglades.JPG'),
    ('01a08376-dc00-7000-8000-000000004104', '01a08376-dc00-7000-8000-000000003004', 'Majestic Princess', 'majestic-princess',
     'https://upload.wikimedia.org/wikipedia/commons/2/26/MAJESTIC_PRINCESS_20180405-1_(cropped).jpg', 'カテキン / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:MAJESTIC_PRINCESS_20180405-1_(cropped).jpg'),
    ('01a08376-dc00-7000-8000-000000004105', '01a08376-dc00-7000-8000-000000003004', 'Regal Princess', 'regal-princess',
     'https://upload.wikimedia.org/wikipedia/commons/7/7d/Rostock_asv2018-05_img63_Warnemuende_port.jpg', 'A.Savin / Wikimedia Commons, FAL', 'FAL', 'https://commons.wikimedia.org/wiki/File:Rostock_asv2018-05_img63_Warnemuende_port.jpg'),
    ('01a08376-dc00-7000-8000-000000004106', '01a08376-dc00-7000-8000-000000003004', 'Royal Princess', 'royal-princess',
     'https://upload.wikimedia.org/wikipedia/commons/f/f5/Royal_Princess_(9038666095).jpg', 'Barry Skeates / Wikimedia Commons, CC BY 2.0', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Royal_Princess_(9038666095).jpg'),
    ('01a08376-dc00-7000-8000-000000004107', '01a08376-dc00-7000-8000-000000003004', 'Ruby Princess', 'ruby-princess',
     'https://upload.wikimedia.org/wikipedia/commons/e/e4/Ruby_Princess_(ship%2C_2008)_IMO_9378462%3B_in_Split%2C_2011-10-17_(2).jpg', 'Ivan T. / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Ruby_Princess_(ship,_2008)_IMO_9378462;_in_Split,_2011-10-17_(2).jpg'),
    ('01a08376-dc00-7000-8000-000000004108', '01a08376-dc00-7000-8000-000000003004', 'Sapphire Princess', 'sapphire-princess',
     'https://upload.wikimedia.org/wikipedia/commons/3/3c/Sapphire_Princess02.JPG', 'Yankeesman312 / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Sapphire_Princess02.JPG'),
    ('01a08376-dc00-7000-8000-000000004109', '01a08376-dc00-7000-8000-000000003004', 'Sky Princess', 'sky-princess',
     'https://upload.wikimedia.org/wikipedia/commons/d/d4/Sky_Princess_(ship%2C_2019)_at_Liverpool_3.jpg', 'Rodhullandemu / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Sky_Princess_(ship,_2019)_at_Liverpool_3.jpg'),
    ('01a08376-dc00-7000-8000-000000004110', '01a08376-dc00-7000-8000-000000003004', 'Star Princess', 'star-princess',
     'https://upload.wikimedia.org/wikipedia/commons/2/22/Star_Princess_Tendering.jpg', 'Yankeesman312 / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Star_Princess_Tendering.jpg'),
    ('01a08376-dc00-7000-8000-000000004111', '01a08376-dc00-7000-8000-000000003004', 'Sun Princess', 'sun-princess',
     NULL, NULL, NULL, NULL),
    ('01a08376-dc00-7000-8000-000000004112', '01a08376-dc00-7000-8000-000000003002', 'Celebrity Apex', 'celebrity-apex',
     'https://upload.wikimedia.org/wikipedia/commons/5/5e/Celebrity_APEX_IMO_9838383_P_Stockholm_15-07-2022.jpg', 'Wolfgang Fricke / Wikimedia Commons, CC BY 3.0', 'CC BY 3.0', 'https://commons.wikimedia.org/wiki/File:Celebrity_APEX_IMO_9838383_P_Stockholm_15-07-2022.jpg'),
    ('01a08376-dc00-7000-8000-000000004113', '01a08376-dc00-7000-8000-000000003002', 'Celebrity Ascent', 'celebrity-ascent',
     'https://upload.wikimedia.org/wikipedia/commons/3/36/Celebrity_Ascent_-_Le_Pir%C3%A9e_-_June_2024.jpg', 'ND44 / Wikimedia Commons, CC BY 4.0', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:Celebrity_Ascent_-_Le_Pir%C3%A9e_-_June_2024.jpg'),
    ('01a08376-dc00-7000-8000-000000004114', '01a08376-dc00-7000-8000-000000003002', 'Celebrity Beyond', 'celebrity-beyond',
     'https://upload.wikimedia.org/wikipedia/commons/b/b2/Celebrity_BEYOND_La_Rochelle.jpg', 'Didier Duforest / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Celebrity_BEYOND_La_Rochelle.jpg'),
    ('01a08376-dc00-7000-8000-000000004115', '01a08376-dc00-7000-8000-000000003002', 'Celebrity Constellation', 'celebrity-constellation',
     'https://upload.wikimedia.org/wikipedia/commons/0/0d/Constellation.jpg', 'Megadri / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Constellation.jpg'),
    ('01a08376-dc00-7000-8000-000000004116', '01a08376-dc00-7000-8000-000000003002', 'Celebrity Eclipse', 'celebrity-eclipse',
     'https://upload.wikimedia.org/wikipedia/commons/3/31/Celebrity_Eclipse_leaving_Southampton.jpg', 'MrDerails at English Wikipedia / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Celebrity_Eclipse_leaving_Southampton.jpg'),
    ('01a08376-dc00-7000-8000-000000004117', '01a08376-dc00-7000-8000-000000003002', 'Celebrity Edge', 'celebrity-edge',
     'https://upload.wikimedia.org/wikipedia/commons/4/47/Celebrity_Edge_-_Sept_2018_(cropped).jpg', 'Jjerome78 / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Celebrity_Edge_-_Sept_2018_(cropped).jpg'),
    ('01a08376-dc00-7000-8000-000000004118', '01a08376-dc00-7000-8000-000000003002', 'Celebrity Equinox', 'celebrity-equinox',
     'https://upload.wikimedia.org/wikipedia/commons/b/b9/CelebrityEquinox-maidenvoyage.jpg', 'This image photographed by Brian Burnell with permission was uploaded to Commons by George Hutchinson . To see his entire portfolio, click here . Permission to upload photographs b / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:CelebrityEquinox-maidenvoyage.jpg'),
    ('01a08376-dc00-7000-8000-000000004119', '01a08376-dc00-7000-8000-000000003002', 'Celebrity Flora', 'celebrity-flora',
     'https://upload.wikimedia.org/wikipedia/commons/2/2a/Celebrity_Flora_IMO_9837925_P_Puerto_Ayora_15-11-2025_(2).jpg', 'Wolfgang Fricke / Wikimedia Commons, CC BY 3.0', 'CC BY 3.0', 'https://commons.wikimedia.org/wiki/File:Celebrity_Flora_IMO_9837925_P_Puerto_Ayora_15-11-2025_(2).jpg'),
    ('01a08376-dc00-7000-8000-000000004120', '01a08376-dc00-7000-8000-000000003002', 'Celebrity Infinity', 'celebrity-infinity',
     'https://upload.wikimedia.org/wikipedia/commons/a/af/Celebrity_Infinity_tendering_at_Juneau%2C_Alaska.jpg', 'Yankeesman312 / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Celebrity_Infinity_tendering_at_Juneau,_Alaska.jpg'),
    ('01a08376-dc00-7000-8000-000000004121', '01a08376-dc00-7000-8000-000000003002', 'Celebrity Millennium', 'celebrity-millennium',
     'https://upload.wikimedia.org/wikipedia/commons/2/28/Millennium-7.JPG', 'Captain-tucker / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Millennium-7.JPG'),
    ('01a08376-dc00-7000-8000-000000004122', '01a08376-dc00-7000-8000-000000003002', 'Celebrity Reflection', 'celebrity-reflection',
     'https://upload.wikimedia.org/wikipedia/commons/a/a2/Celebrity_REFLECTION.jpg', 'Celebrity_REFLECTION_by_Moehre1992.jpg : Moehre1992 derivative work: Hic et nunc / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Celebrity_REFLECTION.jpg'),
    ('01a08376-dc00-7000-8000-000000004123', '01a08376-dc00-7000-8000-000000003002', 'Celebrity Silhouette', 'celebrity-silhouette',
     'https://upload.wikimedia.org/wikipedia/commons/f/fd/Celebrity_Silhouette_San_Juan.JPG', 'Kyle.died.rich / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Celebrity_Silhouette_San_Juan.JPG'),
    ('01a08376-dc00-7000-8000-000000004124', '01a08376-dc00-7000-8000-000000003002', 'Celebrity Solstice', 'celebrity-solstice',
     'https://upload.wikimedia.org/wikipedia/commons/e/eb/Celebrity_Solstice_(ship%2C_2008)_001.jpg', 'Aah-Yeah / Wikimedia Commons, CC BY 2.0', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Celebrity_Solstice_(ship,_2008)_001.jpg'),
    ('01a08376-dc00-7000-8000-000000004125', '01a08376-dc00-7000-8000-000000003002', 'Celebrity Summit', 'celebrity-summit',
     'https://upload.wikimedia.org/wikipedia/commons/f/ff/Celebrity_Summit.jpg', 'Yankeesman312 / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Celebrity_Summit.jpg'),
    ('01a08376-dc00-7000-8000-000000004126', '01a08376-dc00-7000-8000-000000003002', 'Celebrity Xcel', 'celebrity-xcel',
     'https://upload.wikimedia.org/wikipedia/commons/d/d5/Celebrity_Xcel_at_Port_Everglades_2025-11-05.jpg', 'Tunestoons / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Celebrity_Xcel_at_Port_Everglades_2025-11-05.jpg'),
    ('01a08376-dc00-7000-8000-000000004127', '01a08376-dc00-7000-8000-000000003007', 'Eurodam', 'eurodam',
     'https://upload.wikimedia.org/wikipedia/commons/e/eb/2018-09-18_MS_EURODAM_-_IMO_9378448_-_Glacier_Bay%2C_Alaska_USA.jpg', 'Gordon Leggett / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:2018-09-18_MS_EURODAM_-_IMO_9378448_-_Glacier_Bay,_Alaska_USA.jpg'),
    ('01a08376-dc00-7000-8000-000000004128', '01a08376-dc00-7000-8000-000000003007', 'Koningsdam', 'koningsdam',
     'https://upload.wikimedia.org/wikipedia/commons/4/48/Koningsdam_(ship%2C_2016)_004.jpg', 'kees torn / Wikimedia Commons, CC BY-SA 2.0', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:Koningsdam_(ship,_2016)_004.jpg'),
    ('01a08376-dc00-7000-8000-000000004129', '01a08376-dc00-7000-8000-000000003007', 'Nieuw Amsterdam', 'nieuw-amsterdam',
     'https://upload.wikimedia.org/wikipedia/commons/3/37/MS_Nieuw_Amsterdam_2011.JPG', 'Cybergoth / Wikimedia Commons, CC BY-SA 1.0', 'CC BY-SA 1.0', 'https://commons.wikimedia.org/wiki/File:MS_Nieuw_Amsterdam_2011.JPG'),
    ('01a08376-dc00-7000-8000-000000004130', '01a08376-dc00-7000-8000-000000003007', 'Nieuw Statendam', 'nieuw-statendam',
     'https://upload.wikimedia.org/wikipedia/commons/3/3d/NIEUW_STATENDAM_(49895575701).jpg', 'kees torn / Wikimedia Commons, CC BY-SA 2.0', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:NIEUW_STATENDAM_(49895575701).jpg'),
    ('01a08376-dc00-7000-8000-000000004131', '01a08376-dc00-7000-8000-000000003007', 'Noordam', 'noordam',
     'https://upload.wikimedia.org/wikipedia/commons/c/c1/Noordam.jpg', 'MilkoholicBear at English Wikipedia / Wikimedia Commons, Public domain', 'Public domain', 'https://commons.wikimedia.org/wiki/File:Noordam.jpg'),
    ('01a08376-dc00-7000-8000-000000004132', '01a08376-dc00-7000-8000-000000003007', 'Oosterdam', 'oosterdam',
     'https://upload.wikimedia.org/wikipedia/commons/2/20/Croisi%C3%A8res_Oosterdam_%C3%A0_quai.jpg', 'Farid mernissi / Wikimedia Commons, CC BY 4.0', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:Croisi%C3%A8res_Oosterdam_%C3%A0_quai.jpg'),
    ('01a08376-dc00-7000-8000-000000004133', '01a08376-dc00-7000-8000-000000003007', 'Rotterdam', 'rotterdam',
     'https://upload.wikimedia.org/wikipedia/commons/3/34/Rostock_asv2018-05_img67_Warnemuende_port.jpg', 'A.Savin / Wikimedia Commons, FAL', 'FAL', 'https://commons.wikimedia.org/wiki/File:Rostock_asv2018-05_img67_Warnemuende_port.jpg'),
    ('01a08376-dc00-7000-8000-000000004134', '01a08376-dc00-7000-8000-000000003007', 'Volendam', 'volendam',
     'https://upload.wikimedia.org/wikipedia/commons/0/0a/2024-06-10_01_MS_VOLENDAM_-_IMO_9156515_-_Halifax_NS_CAN.jpg', 'Gordon Leggett / Wikimedia Commons, CC BY 4.0', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:2024-06-10_01_MS_VOLENDAM_-_IMO_9156515_-_Halifax_NS_CAN.jpg'),
    ('01a08376-dc00-7000-8000-000000004135', '01a08376-dc00-7000-8000-000000003007', 'Westerdam', 'westerdam',
     'https://upload.wikimedia.org/wikipedia/commons/5/53/Westerdam_in_Costa_Maya_002.jpg', 'Roger Wollstadt / Wikimedia Commons, CC BY-SA 2.0', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:Westerdam_in_Costa_Maya_002.jpg'),
    ('01a08376-dc00-7000-8000-000000004136', '01a08376-dc00-7000-8000-000000003007', 'Zaandam', 'zaandam',
     'https://upload.wikimedia.org/wikipedia/commons/c/ca/MS_Zaandam_en_Castro_(cropped).jpg', 'Draceane / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:MS_Zaandam_en_Castro_(cropped).jpg'),
    ('01a08376-dc00-7000-8000-000000004137', '01a08376-dc00-7000-8000-000000003007', 'Zuiderdam', 'zuiderdam',
     'https://upload.wikimedia.org/wikipedia/commons/4/4b/Zuiderdam_moored_in_Vancouver_cropped.jpg', 'Br100x / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Zuiderdam_moored_in_Vancouver_cropped.jpg'),
    ('01a08376-dc00-7000-8000-000000004138', '01a08376-dc00-7000-8000-000000003003', 'Disney Adventure', 'disney-adventure',
     'https://upload.wikimedia.org/wikipedia/commons/c/c4/Disney_Adventure_Disney_Cruise_Line_(55114526110).jpg', 'nagi usano from Tokyo, Japan / Wikimedia Commons, CC BY 4.0', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:Disney_Adventure_Disney_Cruise_Line_(55114526110).jpg'),
    ('01a08376-dc00-7000-8000-000000004139', '01a08376-dc00-7000-8000-000000003003', 'Disney Destiny', 'disney-destiny',
     'https://upload.wikimedia.org/wikipedia/commons/d/d8/Disney_Destiny_(cropped).jpg', 'Ferriesworldwide / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Disney_Destiny_(cropped).jpg'),
    ('01a08376-dc00-7000-8000-000000004140', '01a08376-dc00-7000-8000-000000003003', 'Disney Dream', 'disney-dream',
     'https://upload.wikimedia.org/wikipedia/commons/f/fa/Disney_Dream_docked_in_the_Bahamas_02.JPG', 'Stratocaster27 / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Disney_Dream_docked_in_the_Bahamas_02.JPG'),
    ('01a08376-dc00-7000-8000-000000004141', '01a08376-dc00-7000-8000-000000003003', 'Disney Fantasy', 'disney-fantasy',
     'https://upload.wikimedia.org/wikipedia/commons/8/80/Disney_Fantasy_arriving_in_New_York.png', 'Stjanss and mriedel / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Disney_Fantasy_arriving_in_New_York.png'),
    ('01a08376-dc00-7000-8000-000000004142', '01a08376-dc00-7000-8000-000000003003', 'Disney Magic', 'disney-magic',
     'https://upload.wikimedia.org/wikipedia/commons/8/86/Disney_Magic2.jpg', '[1] / Wikimedia Commons, CC BY 2.0', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Disney_Magic2.jpg'),
    ('01a08376-dc00-7000-8000-000000004143', '01a08376-dc00-7000-8000-000000003003', 'Disney Treasure', 'disney-treasure',
     'https://upload.wikimedia.org/wikipedia/commons/6/65/Disney_Treasure_schip_(cropped).jpg', 'Seppecool10 / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Disney_Treasure_schip_(cropped).jpg'),
    ('01a08376-dc00-7000-8000-000000004144', '01a08376-dc00-7000-8000-000000003003', 'Disney Wish', 'disney-wish',
     'https://upload.wikimedia.org/wikipedia/commons/7/74/Disney_wish_nassau_08202022.jpg', 'Niamor1484 / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Disney_wish_nassau_08202022.jpg'),
    ('01a08376-dc00-7000-8000-000000004145', '01a08376-dc00-7000-8000-000000003003', 'Disney Wonder', 'disney-wonder',
     'https://upload.wikimedia.org/wikipedia/commons/2/21/Prince_George_Wharf_in_Nassau_Harbor_(Disney_Wonder).jpg', 'TampAGS , for AGS Media / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Prince_George_Wharf_in_Nassau_Harbor_(Disney_Wonder).jpg'),
    ('01a08376-dc00-7000-8000-000000004146', '01a08376-dc00-7000-8000-000000000100', 'Brilliant Lady', 'brilliant-lady',
     'https://upload.wikimedia.org/wikipedia/commons/8/82/Virgin_Voyages_Brilliant_Lady.jpg', 'Aztec246 / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Virgin_Voyages_Brilliant_Lady.jpg'),
    ('01a08376-dc00-7000-8000-000000004147', '01a08376-dc00-7000-8000-000000000100', 'Resilient Lady', 'resilient-lady',
     'https://upload.wikimedia.org/wikipedia/commons/5/5b/Resilient_Lady_docking_at_Sydney.jpg', 'Dicklyon / Wikimedia Commons, CC BY 4.0', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:Resilient_Lady_docking_at_Sydney.jpg'),
    ('01a08376-dc00-7000-8000-000000004148', '01a08376-dc00-7000-8000-000000000100', 'Scarlet Lady', 'scarlet-lady',
     'https://upload.wikimedia.org/wikipedia/commons/0/02/Scarlet_Lady_in_Liverpool_February_2020_(cropped).jpg', 'silver-novice ~ ne res adversae impediant / Wikimedia Commons, CC BY 2.0', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Scarlet_Lady_in_Liverpool_February_2020_(cropped).jpg'),
    ('01a08376-dc00-7000-8000-000000004149', '01a08376-dc00-7000-8000-000000000100', 'Valiant Lady', 'valiant-lady',
     'https://upload.wikimedia.org/wikipedia/commons/0/0f/Valiant_Lady_no_peirao_da_Coru%C3%B1a_1.jpg', 'Estevoaei / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Valiant_Lady_no_peirao_da_Coru%C3%B1a_1.jpg'),
    ('01a08376-dc00-7000-8000-000000004150', '01a08376-dc00-7000-8000-000000003009', 'Queen Anne', 'queen-anne',
     'https://upload.wikimedia.org/wikipedia/commons/7/7f/Ms_queen_anne_southampton.JPG', 'Geni / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Ms_queen_anne_southampton.JPG'),
    ('01a08376-dc00-7000-8000-000000004151', '01a08376-dc00-7000-8000-000000003009', 'Queen Elizabeth', 'queen-elizabeth',
     'https://upload.wikimedia.org/wikipedia/commons/0/0d/Queen_Elizabeth_in_Tallinn_7_July_2011.JPG', 'Pjotr Mahhonin / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Queen_Elizabeth_in_Tallinn_7_July_2011.JPG'),
    ('01a08376-dc00-7000-8000-000000004152', '01a08376-dc00-7000-8000-000000003009', 'Queen Mary 2', 'queen-mary-2',
     'https://upload.wikimedia.org/wikipedia/commons/d/d1/Qm2_portboston_(cropped).jpg', 'Oceanhistory46 / Wikimedia Commons, CC BY-SA 4.0', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Qm2_portboston_(cropped).jpg'),
    ('01a08376-dc00-7000-8000-000000004153', '01a08376-dc00-7000-8000-000000003009', 'Queen Victoria', 'queen-victoria',
     'https://upload.wikimedia.org/wikipedia/commons/c/c5/Queen_Victoria-1.jpg', 'This image photographed by Brian Burnell with permission was uploaded to Commons by George Hutchinson . To see his entire portfolio, click here . Permission to upload photographs b / Wikimedia Commons, CC BY-SA 3.0', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Queen_Victoria-1.jpg')
ON CONFLICT (cruise_line_id, name) DO UPDATE
    SET image_url        = excluded.image_url,
        image_credit     = excluded.image_credit,
        image_license    = excluded.image_license,
        image_source_url = excluded.image_source_url
    WHERE cruise_ship.image_url IS NULL AND excluded.image_url IS NOT NULL;

-- This assertion bites, unlike one written over rows that seed.sql supplies later: the counts
-- below are of rows this same migration just wrote, in the same transaction.
DO $$
DECLARE
    lines_found integer;
    ships_found integer;
BEGIN
    SELECT count(*) INTO lines_found FROM public.cruise_line;
    SELECT count(*) INTO ships_found FROM public.cruise_ship;

    IF lines_found <> 10 THEN
        RAISE EXCEPTION 'expected 10 cruise lines after the fleet insert, found %', lines_found;
    END IF;
    IF ships_found <> 153 THEN
        RAISE EXCEPTION 'expected 153 cruise ships after the fleet insert, found %', ships_found;
    END IF;
END $$;
