import type { Money, Trip } from "./types";

/**
 * Gyasi's curated catalog — every trip named across the 2.0 prototypes
 * (design/source-prototype/screens/client-public.jsx, client-public-topics.jsx,
 * client-public-mobile.jsx), deduplicated by slug. Two resorts appear on both the
 * Caribbean and Honeymoons pages and carry per-topic placements.
 *
 * PRICES ARE PLACEHOLDERS. The prototype prices four trips ("design"); the rest carry a
 * figure consistent with Gyasi's $ / $$ / $$$ band ("illustrative"). Every page that shows
 * a price also shows the "request a quote to see real prices" line, and the claims registry
 * (proof.ts) blocks a production build while `pricePlaceholder` is true anywhere.
 *
 * Descriptions, highlights and sample itineraries are drafted from the prototype copy and
 * broadly known public information about each property or ship; suppliers must confirm
 * them before launch (registry claim `tripDetails`).
 */

const usd = (dollars: number): Money => ({ amountCents: dollars * 100, currency: "USD" });
const AS_OF = "2026-09-02";
const DESIGN_NOTE = "Starting price shown in the design — request a quote for real prices on your dates.";
const ILLUSTRATIVE_NOTE = "Illustrative starting price — request a quote for real prices on your dates.";

export const TRIPS: readonly Trip[] = [
  // ── Caribbean (2.0.8), in tile order ─────────────────────────────────────────
  {
    slug: "beaches-turks-and-caicos",
    name: "Beaches Turks & Caicos",
    tagline: "Providenciales · Family all-inclusive",
    overline: "ALL-INCLUSIVE · FAMILY",
    type: "all-inclusive",
    vibes: ["family"],
    topics: { caribbean: { order: 1, badge: "Gyasi's pick" } },
    destination: { place: "Providenciales, Turks & Caicos", region: "Caribbean", island: "turks-and-caicos" },
    nights: 7,
    band: "$$",
    from: usd(2640),
    priceAsOf: AS_OF,
    pricePlaceholder: true,
    priceSource: "design",
    priceNote: DESIGN_NOTE,
    badge: "Gyasi's pick",
    imageKey: "turks",
    description:
      "Grace Bay's long white beach out front, a waterpark the kids will talk about for a year, and enough places to eat that nobody has to agree on dinner. Built for families who want the week handled before they land.",
    highlights: [
      { icon: "users", text: "Family suites and kids' camps by age" },
      { icon: "palm", text: "Grace Bay beach on your doorstep" },
      { icon: "utensils", text: "Every meal and snack included" },
      { icon: "plane", text: "Flights and transfers arranged for you" },
    ],
    sampleItinerary: [
      "Day 1 · Arrive, unpack once, first sunset on Grace Bay",
      "Day 2 · Waterpark morning, quiet beach afternoon",
      "Day 3 · Reef snorkel trip for the whole family",
      "Day 4 · Resort day — spa for the grown-ups, kids' camp for the rest",
    ],
  },
  {
    slug: "sandals-royal-bahamian",
    name: "Sandals Royal Bahamian",
    tagline: "Nassau · Adults-only · 7 nights",
    overline: "ALL-INCLUSIVE · ADULTS",
    type: "all-inclusive",
    vibes: ["adults-only", "couples", "honeymoon"],
    topics: {
      caribbean: { order: 2 },
      honeymoons: { order: 6, tagline: "Nassau · Private island day · 7 nights" },
    },
    destination: { place: "Nassau, Bahamas", region: "Caribbean", island: "bahamas" },
    nights: 7,
    band: "$$$",
    from: usd(3290),
    priceAsOf: AS_OF,
    pricePlaceholder: true,
    priceSource: "design",
    priceNote: "All-in · flights, transfers, all meals, drinks, activities",
    imageKey: "bahamas",
    heroImageKey: "overwater",
    description:
      "Over-water bungalows, six pools, twelve dining venues, a Red Lane spa, and a private island day. Adults-only — built for honeymoons, anniversaries, and “just us” weeks.",
    highlights: [
      { icon: "plane", text: "Flights included from MIA" },
      { icon: "utensils", text: "12 restaurants" },
      { icon: "heart", text: "Red Lane spa credit" },
      { icon: "ship", text: "Day-trip to Rose Island" },
    ],
    sampleItinerary: [
      "Day 1 · Arrival & sunset welcome",
      "Day 2 · Beach + Red Lane spa",
      "Day 3 · Rose Island Cay snorkel",
      "Day 4 · Resort day",
    ],
  },
  {
    slug: "sandals-grande-st-lucian",
    name: "Sandals Grande St. Lucian",
    tagline: "Rodney Bay, St. Lucia · Overwater bungalows · 7 nights",
    overline: "ALL-INCLUSIVE · COUPLES",
    type: "all-inclusive",
    vibes: ["adults-only", "couples", "honeymoon"],
    topics: {
      caribbean: { order: 3, tagline: "Rodney Bay · Lush rainforest views" },
      honeymoons: { order: 1, overline: "OVERWATER · ADULTS", tagline: "St. Lucia · Overwater bungalows · 7 nights", badge: "Gyasi's pick" },
    },
    destination: { place: "Rodney Bay, St. Lucia", region: "Caribbean", island: "st-lucia" },
    nights: 7,
    band: "$$$",
    from: usd(3890),
    priceAsOf: AS_OF,
    pricePlaceholder: true,
    priceSource: "illustrative",
    priceNote: ILLUSTRATIVE_NOTE,
    imageKey: "stlucia",
    description:
      "A calm bay on one side, the Pitons on the horizon, and a handful of over-water bungalows for the couples who want the ocean under the floorboards. The spa here is the one Gyasi sends honeymooners to first.",
    highlights: [
      { icon: "heart", text: "Over-water bungalows with glass floors" },
      { icon: "palm", text: "Rainforest and Piton views" },
      { icon: "utensils", text: "All meals, drinks and dining venues included" },
      { icon: "plane", text: "Flights and transfers arranged for you" },
    ],
    sampleItinerary: [
      "Day 1 · Arrive, settle in, dinner over the water",
      "Day 2 · Spa morning, bay afternoon",
      "Day 3 · Piton catamaran day",
      "Day 4 · Nothing planned — on purpose",
    ],
  },
  {
    slug: "couples-negril",
    name: "Couples Negril",
    tagline: "Negril · Quiet, all-inclusive, no kids",
    overline: "ALL-INCLUSIVE · COUPLES",
    type: "all-inclusive",
    vibes: ["adults-only", "couples"],
    topics: { caribbean: { order: 4 } },
    destination: { place: "Negril, Jamaica", region: "Caribbean", island: "jamaica" },
    nights: 7,
    band: "$$",
    from: usd(2180),
    priceAsOf: AS_OF,
    pricePlaceholder: true,
    priceSource: "design",
    priceNote: DESIGN_NOTE,
    imageKey: "jamaica",
    description:
      "Seven-mile beach, a slower pace, and a resort that has been quietly good for decades. No kids, no upsells, no reason to look at your phone. The week Gyasi suggests when a couple says “we just need to stop.”",
    highlights: [
      { icon: "palm", text: "Seven Mile Beach" },
      { icon: "heart", text: "Couples-only, unhurried" },
      { icon: "utensils", text: "Meals, drinks and excursions included" },
      { icon: "ship", text: "Sunset catamaran sail" },
    ],
    sampleItinerary: [
      "Day 1 · Arrive, first swim before dinner",
      "Day 2 · Beach day, glass-bottom boat",
      "Day 3 · Cliff-jumping (optional) and reggae sunset",
      "Day 4 · Spa and a long, slow lunch",
    ],
  },
  {
    slug: "bucuti-and-tara",
    name: "Bucuti & Tara Beach Resort",
    tagline: "Eagle Beach, Aruba · Boutique adult-only",
    overline: "BOUTIQUE · ADULTS",
    type: "hotel",
    vibes: ["adults-only", "boutique", "couples"],
    topics: { caribbean: { order: 5, tagline: "Eagle Beach · Boutique adult-only" } },
    destination: { place: "Eagle Beach, Aruba", region: "Caribbean", island: "aruba" },
    nights: 7,
    band: "$$$",
    from: usd(3450),
    priceAsOf: AS_OF,
    pricePlaceholder: true,
    priceSource: "illustrative",
    priceNote: ILLUSTRATIVE_NOTE,
    imageKey: "aruba",
    description:
      "A small, adults-only resort on one of the Caribbean's widest beaches, in the island with the most reliable sunshine. Quiet by design — for couples who want a boutique feel rather than a big all-inclusive.",
    highlights: [
      { icon: "palm", text: "Eagle Beach, steps from your room" },
      { icon: "heart", text: "Adults-only, boutique scale" },
      { icon: "star", text: "Consistently sunny, outside the hurricane belt" },
      { icon: "utensils", text: "Beachfront dining" },
    ],
    sampleItinerary: [
      "Day 1 · Arrive, sunset on Eagle Beach",
      "Day 2 · Beach palapa and a long swim",
      "Day 3 · Arikok National Park half-day",
      "Day 4 · Spa and an island-side dinner",
    ],
  },
  {
    slug: "atlantis-paradise-island",
    name: "Atlantis Paradise Island",
    tagline: "Nassau · Waterpark + family suites",
    overline: "RESORT · FAMILY",
    type: "hotel",
    vibes: ["family", "group"],
    topics: { caribbean: { order: 6 } },
    destination: { place: "Paradise Island, Bahamas", region: "Caribbean", island: "bahamas" },
    nights: 5,
    band: "$$",
    from: usd(2190),
    priceAsOf: AS_OF,
    pricePlaceholder: true,
    priceSource: "illustrative",
    priceNote: ILLUSTRATIVE_NOTE,
    imageKey: "bahamas",
    description:
      "The big one: waterpark, aquarium, lagoons, and enough towers that Gyasi will steer you to the right one for your family's age range and budget. Not an all-inclusive — which is why having someone plan the meals matters.",
    highlights: [
      { icon: "users", text: "Waterpark and aquarium on property" },
      { icon: "star", text: "Towers for every budget" },
      { icon: "plane", text: "Short flights from most of the East Coast" },
      { icon: "utensils", text: "Dining plan options Gyasi will explain" },
    ],
    sampleItinerary: [
      "Day 1 · Arrive, lagoon swim before dinner",
      "Day 2 · Waterpark from opening bell",
      "Day 3 · Aquarium morning, beach afternoon",
      "Day 4 · Nassau day trip or a slow pool day",
    ],
  },
  {
    slug: "excellence-oyster-bay",
    name: "Excellence Oyster Bay",
    tagline: "Falmouth, Jamaica · Adults-only all-inclusive",
    overline: "ALL-INCLUSIVE · ADULTS",
    type: "all-inclusive",
    vibes: ["adults-only", "couples"],
    topics: { caribbean: { order: 7, tagline: "Falmouth · Adults-only all-inclusive" } },
    destination: { place: "Falmouth, Jamaica", region: "Caribbean", island: "jamaica" },
    nights: 7,
    band: "$$",
    from: usd(2360),
    priceAsOf: AS_OF,
    pricePlaceholder: true,
    priceSource: "illustrative",
    priceNote: ILLUSTRATIVE_NOTE,
    imageKey: "jamaica",
    description:
      "An adults-only all-inclusive on its own peninsula between Montego Bay and Ocho Rios. Over-water bungalows, swim-up suites, and a quieter stretch of Jamaica than the big-resort strips.",
    highlights: [
      { icon: "heart", text: "Over-water and swim-up suites" },
      { icon: "palm", text: "Private peninsula, calm water" },
      { icon: "utensils", text: "All dining and drinks included" },
      { icon: "plane", text: "About 40 minutes from Montego Bay airport" },
    ],
    sampleItinerary: [
      "Day 1 · Arrive, first dinner by the water",
      "Day 2 · Pool and beach, no agenda",
      "Day 3 · Dunn's River Falls day trip",
      "Day 4 · Spa and a sunset sail",
    ],
  },
  {
    slug: "bvi-sailing-charter",
    name: "BVI sailing charter",
    tagline: "7-night skippered catamaran",
    overline: "SAILING · GROUP",
    type: "tour",
    vibes: ["group", "adventure", "couples"],
    topics: { caribbean: { order: 8, badge: "Great for groups" } },
    destination: { place: "British Virgin Islands", region: "Caribbean", island: "bvi" },
    nights: 7,
    band: "$$$",
    from: usd(4950),
    priceAsOf: AS_OF,
    pricePlaceholder: true,
    priceSource: "illustrative",
    priceNote: ILLUSTRATIVE_NOTE,
    badge: "Great for groups",
    imageKey: "bvi",
    description:
      "A skippered catamaran for six to ten people, island-hopping the BVI for a week. Somebody else sails, cooks and picks the anchorage; you snorkel, read, and watch the light change. Gyasi's favorite way to do a friends' week.",
    highlights: [
      { icon: "ship", text: "Skippered catamaran, your own itinerary" },
      { icon: "users", text: "Best for 6–10 travelers" },
      { icon: "palm", text: "A new anchorage every night" },
      { icon: "star", text: "Snorkel straight off the boat" },
    ],
    sampleItinerary: [
      "Day 1 · Board in Tortola, first anchorage by sunset",
      "Day 2 · The Baths at Virgin Gorda",
      "Day 3 · Anegada's reef and beach bars",
      "Day 4 · Jost Van Dyke, an easy afternoon",
    ],
  },
  {
    slug: "beaches-negril",
    name: "Beaches Negril",
    tagline: "Negril · Sesame Street + 7 beaches",
    overline: "ALL-INCLUSIVE · FAMILY",
    type: "all-inclusive",
    vibes: ["family"],
    topics: { caribbean: { order: 9 } },
    destination: { place: "Negril, Jamaica", region: "Caribbean", island: "jamaica" },
    nights: 7,
    band: "$$",
    from: usd(2480),
    priceAsOf: AS_OF,
    pricePlaceholder: true,
    priceSource: "illustrative",
    priceNote: ILLUSTRATIVE_NOTE,
    imageKey: "overwater",
    description:
      "The family Beaches on Seven Mile Beach: character breakfasts for the little ones, a waterpark for the middle ones, and a quiet corner for the parents. Everything included, so the only decision is which beach.",
    highlights: [
      { icon: "users", text: "Kids' camps and character programming" },
      { icon: "palm", text: "Seven Mile Beach" },
      { icon: "utensils", text: "All meals, snacks and drinks included" },
      { icon: "plane", text: "Flights and transfers arranged for you" },
    ],
    sampleItinerary: [
      "Day 1 · Arrive, beach before dinner",
      "Day 2 · Waterpark and character breakfast",
      "Day 3 · Glass-bottom boat and reef swim",
      "Day 4 · Parents' spa morning, kids' camp",
    ],
  },

  // ── Cruises (2.0.9), in tile order ───────────────────────────────────────────
  {
    slug: "symphony-of-the-seas",
    name: "Symphony of the Seas",
    line: "Royal Caribbean",
    tagline: "Eastern Caribbean · 7 nights · From Miami",
    overline: "ROYAL CARIBBEAN",
    type: "cruise",
    vibes: ["family", "group"],
    topics: { cruises: { order: 1, badge: "Gyasi's pick" } },
    destination: { place: "Eastern Caribbean from Miami", region: "Caribbean" },
    nights: 7,
    band: "$$",
    from: usd(1850),
    priceAsOf: AS_OF,
    pricePlaceholder: true,
    priceSource: "design",
    priceNote: DESIGN_NOTE,
    badge: "Gyasi's pick",
    imageKey: "cruiseShip",
    description:
      "One of the biggest ships afloat, which is exactly the point for a multi-generation family: a waterslide deck for the kids, a quiet solarium for the grandparents, and a private island day at Perfect Day at CocoCay.",
    highlights: [
      { icon: "users", text: "Built for multi-gen families" },
      { icon: "ship", text: "Perfect Day at CocoCay" },
      { icon: "utensils", text: "Dozens of dining venues" },
      { icon: "plane", text: "Sails from Miami" },
    ],
    sampleItinerary: [
      "Day 1 · Board in Miami, sail-away on deck",
      "Day 2 · Perfect Day at CocoCay",
      "Day 3 · Sea day — waterslides and the solarium",
      "Day 4 · St. Thomas beach day",
    ],
  },
  {
    slug: "disney-fantasy",
    name: "Disney Fantasy",
    line: "Disney",
    tagline: "Western Caribbean · 7 nights · Castaway Cay",
    overline: "DISNEY · FAMILY",
    type: "cruise",
    vibes: ["family"],
    topics: { cruises: { order: 2 } },
    destination: { place: "Western Caribbean from Port Canaveral", region: "Caribbean" },
    nights: 7,
    band: "$$$",
    from: usd(3420),
    priceAsOf: AS_OF,
    pricePlaceholder: true,
    priceSource: "illustrative",
    priceNote: ILLUSTRATIVE_NOTE,
    imageKey: "cruiseAerial",
    description:
      "The Disney week: character meet-ups, rotational dining, a kids' club that parents have to drag children out of, and Castaway Cay. Pricier than the other family lines, and Gyasi will tell you honestly when it is worth it.",
    highlights: [
      { icon: "users", text: "Kids' clubs by age, nursery too" },
      { icon: "ship", text: "Castaway Cay private island" },
      { icon: "star", text: "Rotational dining with your servers" },
      { icon: "plane", text: "Sails from Port Canaveral" },
    ],
    sampleItinerary: [
      "Day 1 · Board, sail-away party",
      "Day 2 · Sea day — shows and pool deck",
      "Day 3 · Cozumel",
      "Day 4 · Castaway Cay",
    ],
  },
  {
    slug: "celebrity-edge",
    name: "Celebrity Edge",
    line: "Celebrity",
    tagline: "Southern Caribbean · 11 nights · Curaçao + Aruba",
    overline: "CELEBRITY · ADULTS",
    type: "cruise",
    vibes: ["adults-only", "couples", "five-star"],
    topics: { cruises: { order: 3 } },
    destination: { place: "Southern Caribbean from Fort Lauderdale", region: "Caribbean" },
    nights: 11,
    band: "$$$",
    from: usd(3980),
    priceAsOf: AS_OF,
    pricePlaceholder: true,
    priceSource: "illustrative",
    priceNote: ILLUSTRATIVE_NOTE,
    imageKey: "cruiseShip",
    description:
      "A quieter, grown-up ship with real dining and a longer route into the southern Caribbean — Curaçao, Aruba, Bonaire. For couples who want the cruise without the waterslides.",
    highlights: [
      { icon: "heart", text: "Grown-up pace, premium dining" },
      { icon: "ship", text: "Curaçao, Aruba, Bonaire" },
      { icon: "star", text: "Infinite Veranda staterooms" },
      { icon: "plane", text: "Sails from Fort Lauderdale" },
    ],
    sampleItinerary: [
      "Day 1 · Board in Fort Lauderdale",
      "Day 2 · Sea day — rooftop garden and spa",
      "Day 3 · Sea day",
      "Day 4 · Aruba",
    ],
  },
  {
    slug: "sky-princess",
    name: "Sky Princess",
    line: "Princess",
    tagline: "Bahamas · 4 nights · Quick getaway",
    overline: "PRINCESS · WEEKEND",
    type: "cruise",
    vibes: ["couples"],
    topics: { cruises: { order: 4 } },
    destination: { place: "Bahamas from Fort Lauderdale", region: "Caribbean" },
    nights: 4,
    band: "$",
    from: usd(890),
    priceAsOf: AS_OF,
    pricePlaceholder: true,
    priceSource: "illustrative",
    priceNote: ILLUSTRATIVE_NOTE,
    imageKey: "bahamas",
    description:
      "Four nights, one long weekend, no vacation days to negotiate. A short Bahamas loop for couples who need a reset more than a big trip.",
    highlights: [
      { icon: "clock", text: "Long-weekend length" },
      { icon: "ship", text: "Princess Cays beach day" },
      { icon: "utensils", text: "Meals included on board" },
      { icon: "plane", text: "Sails from Fort Lauderdale" },
    ],
    sampleItinerary: [
      "Day 1 · Board Thursday afternoon",
      "Day 2 · Princess Cays",
      "Day 3 · Nassau",
      "Day 4 · Sea day, home Monday",
    ],
  },
  {
    slug: "virgin-resilient-lady",
    name: "Virgin Resilient Lady",
    line: "Virgin Voyages",
    tagline: "Adults-only · 5 nights · Puerto Plata",
    overline: "VIRGIN · ADULTS",
    type: "cruise",
    vibes: ["adults-only", "couples"],
    topics: { cruises: { order: 5 } },
    destination: { place: "Dominican Republic from Miami", region: "Caribbean" },
    nights: 5,
    band: "$$",
    from: usd(1620),
    priceAsOf: AS_OF,
    pricePlaceholder: true,
    priceSource: "illustrative",
    priceNote: ILLUSTRATIVE_NOTE,
    imageKey: "cruiseAerial",
    description:
      "Adults only, no buffets, no formal nights, and a beach club in Bimini. Virgin's ships are for couples and friend groups who want the cruise energy without the kids' pool.",
    highlights: [
      { icon: "heart", text: "Adults-only, no formal nights" },
      { icon: "utensils", text: "Restaurants instead of buffets" },
      { icon: "ship", text: "Beach Club at Bimini" },
      { icon: "plane", text: "Sails from Miami" },
    ],
    sampleItinerary: [
      "Day 1 · Board in Miami",
      "Day 2 · Puerto Plata",
      "Day 3 · Sea day",
      "Day 4 · Beach Club at Bimini",
    ],
  },
  {
    slug: "carnival-celebration",
    name: "Carnival Celebration",
    line: "Carnival",
    tagline: "Eastern Caribbean · 6 nights · Family-priced",
    overline: "CARNIVAL · FAMILY",
    type: "cruise",
    vibes: ["family", "group"],
    topics: { cruises: { order: 6 } },
    destination: { place: "Eastern Caribbean from Miami", region: "Caribbean" },
    nights: 6,
    band: "$",
    from: usd(990),
    priceAsOf: AS_OF,
    pricePlaceholder: true,
    priceSource: "illustrative",
    priceNote: ILLUSTRATIVE_NOTE,
    imageKey: "cruiseShip",
    description:
      "The best-value big-ship week for a family: a roller coaster at sea, a huge waterpark deck, and prices that leave room for excursions. Gyasi's pick when the budget matters more than the brand.",
    highlights: [
      { icon: "users", text: "Family-priced staterooms" },
      { icon: "star", text: "BOLT roller coaster at sea" },
      { icon: "ship", text: "Eastern Caribbean ports" },
      { icon: "plane", text: "Sails from Miami" },
    ],
    sampleItinerary: [
      "Day 1 · Board in Miami",
      "Day 2 · Sea day — waterpark and the coaster",
      "Day 3 · Amber Cove",
      "Day 4 · St. Thomas",
    ],
  },
  {
    slug: "holland-america-eurodam",
    name: "Holland America Eurodam",
    line: "Holland America",
    tagline: "Panama Canal · 11 nights · Bucket-list",
    overline: "HAL · GROUP",
    type: "cruise",
    vibes: ["group", "couples"],
    topics: { cruises: { order: 7 } },
    destination: { place: "Panama Canal from Fort Lauderdale", region: "Panama Canal" },
    nights: 11,
    band: "$$$",
    from: usd(3790),
    priceAsOf: AS_OF,
    pricePlaceholder: true,
    priceSource: "illustrative",
    priceNote: ILLUSTRATIVE_NOTE,
    imageKey: "cruiseAerial",
    description:
      "A bucket-list route through the Panama Canal on a mid-size ship with a slower rhythm — lectures, live music, long dinners. The trip Gyasi plans for reunions and milestone birthdays.",
    highlights: [
      { icon: "ship", text: "Full Panama Canal transit day" },
      { icon: "users", text: "Group rates and a coordinator" },
      { icon: "star", text: "Mid-size ship, unhurried pace" },
      { icon: "plane", text: "Sails from Fort Lauderdale" },
    ],
    sampleItinerary: [
      "Day 1 · Board in Fort Lauderdale",
      "Day 2 · Half Moon Cay",
      "Day 3 · Sea day",
      "Day 4 · Cartagena",
    ],
  },
  {
    slug: "norwegian-encore",
    name: "Norwegian Encore",
    line: "Norwegian",
    tagline: "Bermuda · 7 nights · Pink-sand beaches",
    overline: "NCL · FAMILY",
    type: "cruise",
    vibes: ["family"],
    topics: { cruises: { order: 8 } },
    destination: { place: "Bermuda from New York", region: "Bermuda" },
    nights: 7,
    band: "$$",
    from: usd(1790),
    priceAsOf: AS_OF,
    pricePlaceholder: true,
    priceSource: "illustrative",
    priceNote: ILLUSTRATIVE_NOTE,
    imageKey: "bahamas",
    description:
      "Sail from New York, no flights needed, and spend the middle of the week docked in Bermuda with pink-sand beaches a short ferry away. A different kind of cruise week for East Coast families.",
    highlights: [
      { icon: "plane", text: "Sails from New York — no flights" },
      { icon: "palm", text: "Two-plus days docked in Bermuda" },
      { icon: "users", text: "Go-karts and a laser-tag deck" },
      { icon: "utensils", text: "Freestyle dining, eat when you like" },
    ],
    sampleItinerary: [
      "Day 1 · Board in Manhattan",
      "Day 2 · Sea day — race track and pool deck",
      "Day 3 · Sea day",
      "Day 4 · Bermuda, Horseshoe Bay beach",
    ],
  },
  {
    slug: "wonder-of-the-seas",
    name: "Wonder of the Seas",
    line: "Royal Caribbean",
    tagline: "Western Caribbean · 7 nights · Mahogany Bay",
    overline: "ROYAL · FAMILY",
    type: "cruise",
    vibes: ["family", "group"],
    topics: { cruises: { order: 9 } },
    destination: { place: "Western Caribbean from Port Canaveral", region: "Caribbean" },
    nights: 7,
    band: "$$",
    from: usd(1990),
    priceAsOf: AS_OF,
    pricePlaceholder: true,
    priceSource: "illustrative",
    priceNote: ILLUSTRATIVE_NOTE,
    imageKey: "cruiseShip",
    description:
      "Royal Caribbean's family flagship on the western loop — Roatán's Mahogany Bay, Costa Maya, Cozumel — with a suite neighborhood that makes a big group feel like it has its own corner of the ship.",
    highlights: [
      { icon: "users", text: "Suite neighborhood for big groups" },
      { icon: "ship", text: "Mahogany Bay, Costa Maya, Cozumel" },
      { icon: "star", text: "Waterslides, ice rink, surf simulator" },
      { icon: "plane", text: "Sails from Port Canaveral" },
    ],
    sampleItinerary: [
      "Day 1 · Board in Port Canaveral",
      "Day 2 · Perfect Day at CocoCay",
      "Day 3 · Sea day",
      "Day 4 · Roatán, Mahogany Bay",
    ],
  },

  // ── Honeymoons (2.0.10) — the four not already above ─────────────────────────
  {
    slug: "couples-sans-souci",
    name: "Couples Sans Souci",
    tagline: "Ocho Rios, Jamaica · Cliffside · 7 nights",
    overline: "BOUTIQUE · ADULTS",
    type: "all-inclusive",
    vibes: ["adults-only", "couples", "honeymoon", "boutique"],
    topics: { honeymoons: { order: 2 } },
    destination: { place: "Ocho Rios, Jamaica", region: "Caribbean", island: "jamaica" },
    nights: 7,
    band: "$$",
    from: usd(2590),
    priceAsOf: AS_OF,
    pricePlaceholder: true,
    priceSource: "illustrative",
    priceNote: ILLUSTRATIVE_NOTE,
    imageKey: "jamaica",
    description:
      "Built into a hillside above two coves, with a natural mineral spring pool and a quieter, older-Jamaica feel. A honeymoon resort for couples who want charm over scale.",
    highlights: [
      { icon: "heart", text: "Cliffside suites over two coves" },
      { icon: "star", text: "Mineral spring pool" },
      { icon: "utensils", text: "All dining, drinks and excursions included" },
      { icon: "plane", text: "About 90 minutes from Montego Bay" },
    ],
    sampleItinerary: [
      "Day 1 · Arrive, first dinner above the cove",
      "Day 2 · Mineral pool morning, beach afternoon",
      "Day 3 · Dunn's River Falls",
      "Day 4 · Spa day for two",
    ],
  },
  {
    slug: "excellence-playa-mujeres",
    name: "Excellence Playa Mujeres",
    tagline: "Cancún · Adults-only · Beachfront swim-up",
    overline: "ALL-INCLUSIVE",
    type: "all-inclusive",
    vibes: ["adults-only", "couples", "honeymoon"],
    topics: { honeymoons: { order: 3 } },
    destination: { place: "Playa Mujeres, Cancún, Mexico", region: "Mexico" },
    nights: 7,
    band: "$$",
    from: usd(2290),
    priceAsOf: AS_OF,
    pricePlaceholder: true,
    priceSource: "illustrative",
    priceNote: ILLUSTRATIVE_NOTE,
    imageKey: "aruba",
    description:
      "North of the Cancún hotel zone, on a calmer beach, with swim-up suites and a long list of restaurants. The best-value honeymoon all-inclusive Gyasi plans outside the Caribbean.",
    highlights: [
      { icon: "heart", text: "Swim-up suites, adults-only" },
      { icon: "palm", text: "Quiet beach away from the hotel zone" },
      { icon: "utensils", text: "Ten-plus restaurants included" },
      { icon: "plane", text: "Short transfer from Cancún airport" },
    ],
    sampleItinerary: [
      "Day 1 · Arrive, swim-up pool before dinner",
      "Day 2 · Beach day",
      "Day 3 · Isla Mujeres by ferry",
      "Day 4 · Spa and a slow dinner",
    ],
  },
  {
    slug: "le-blanc-spa-resort",
    name: "Le Blanc Spa Resort",
    tagline: "Cancún · Five-star · Couples-focused",
    overline: "LUXURY · ADULTS",
    type: "all-inclusive",
    vibes: ["adults-only", "couples", "honeymoon", "five-star"],
    topics: { honeymoons: { order: 4 } },
    destination: { place: "Cancún, Mexico", region: "Mexico" },
    nights: 7,
    band: "$$$",
    from: usd(4120),
    priceAsOf: AS_OF,
    pricePlaceholder: true,
    priceSource: "illustrative",
    priceNote: ILLUSTRATIVE_NOTE,
    imageKey: "overwater",
    description:
      "The five-star, butler-service, spa-first honeymoon. Everything is included and everything is quiet. For the couple who wants one week of being completely looked after.",
    highlights: [
      { icon: "star", text: "Butler service, five-star throughout" },
      { icon: "heart", text: "Spa-focused, adults-only" },
      { icon: "utensils", text: "Fine dining included" },
      { icon: "plane", text: "Twenty minutes from Cancún airport" },
    ],
    sampleItinerary: [
      "Day 1 · Arrive, unpacked for you, dinner on the terrace",
      "Day 2 · Spa morning, beach afternoon",
      "Day 3 · Private Chichén Itzá day (optional)",
      "Day 4 · Nothing planned — on purpose",
    ],
  },
  {
    slug: "hamanasi-resort",
    name: "Hamanasi Resort",
    tagline: "Belize · Adventure + beach hybrid",
    overline: "ADVENTURE",
    type: "hotel",
    vibes: ["adventure", "couples", "honeymoon", "boutique"],
    topics: { honeymoons: { order: 5, badge: "Off-the-beaten" } },
    destination: { place: "Hopkins, Belize", region: "Belize" },
    nights: 7,
    band: "$$",
    from: usd(2890),
    priceAsOf: AS_OF,
    pricePlaceholder: true,
    priceSource: "illustrative",
    priceNote: ILLUSTRATIVE_NOTE,
    badge: "Off-the-beaten",
    imageKey: "snorkel",
    description:
      "Half beach, half jungle: a small eco-resort on the Belize coast with guided reef dives one day and Mayan ruins the next. For couples who would rather earn their rest than lie down for it.",
    highlights: [
      { icon: "star", text: "Belize Barrier Reef dives and snorkels" },
      { icon: "palm", text: "Jungle treehouses and beach rooms" },
      { icon: "map", text: "Guided ruins and river trips" },
      { icon: "utensils", text: "Meals and adventures bundled" },
    ],
    sampleItinerary: [
      "Day 1 · Arrive, beach dinner",
      "Day 2 · Reef snorkel or dive",
      "Day 3 · Mayan ruins and cave river",
      "Day 4 · Hammock day",
    ],
  },
];

export function findTrip(slug: string): Trip | undefined {
  return TRIPS.find((t) => t.slug === slug);
}

export const TRIP_SLUGS: readonly string[] = TRIPS.map((t) => t.slug);
